/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyectomp;
import java.awt.Event;
import java.awt.event.KeyEvent;
import java.text.SimpleDateFormat;
import java.time.LocalDate;
import java.time.Period;
import java.time.format.DateTimeFormatter;
import java.util.Calendar;
import java.util.Date;
import javax.swing.InputMap;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.KeyStroke;
import javax.swing.table.DefaultTableModel;
import static proyectomp.DETALLE_PLANILLAS.tblMostrarEmp;
import static proyectomp.EMPLEADOSS_CREAR.labefechReg;
import static proyectomp.PROVEEDOR_1.lblValor;

/**
 *
 * @author espin
 */
public class COMPRA_MATERIA_PRIMA extends javax.swing.JFrame {

    /**
     * Creates new form COMPRA_MATERIA_PRIMA
     */
    public COMPRA_MATERIA_PRIMA() {
        initComponents();
        InputMap ctrl = txtBusqueda.getInputMap(JTextField.WHEN_FOCUSED); 
    ctrl.put(KeyStroke.getKeyStroke(KeyEvent.VK_V, Event.CTRL_MASK), "null");
    InputMap ctrl1 = txtPrecio.getInputMap(JTextField.WHEN_FOCUSED); 
    ctrl1.put(KeyStroke.getKeyStroke(KeyEvent.VK_V, Event.CTRL_MASK), "null");
    InputMap ctrl2 = txtCantidad.getInputMap(JTextField.WHEN_FOCUSED); 
    ctrl2.put(KeyStroke.getKeyStroke(KeyEvent.VK_V, Event.CTRL_MASK), "null");
        this.setLocationRelativeTo(null);
        tblInventario.setSelectionMode(NORMAL);
        tblDetalleCompra.setSelectionMode(NORMAL);
        Funciones_Henry.setListarInventario("");
        setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        ((JTextField)this.txtFechaCompra.getDateEditor()).setEditable(false);
        
        Date fecha = new Date();
        SimpleDateFormat formato = new SimpleDateFormat("yyy-MM-dd");
        lblFechaRegistro.setText(formato.format(fecha));
        
        this.lblId.setText(Funciones_Henry.extraerIdMaxCompra());
        tblInventario.getTableHeader().setReorderingAllowed(false);
        tblDetalleCompra.getTableHeader().setReorderingAllowed(false);
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        btnBuscar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lblId = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtFechaCompra = new com.toedter.calendar.JDateChooser();
        lblFechaRegistro = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        lblNombre = new javax.swing.JLabel();
        lblTelefono = new javax.swing.JLabel();
        lblEmail = new javax.swing.JLabel();
        lblRTN = new javax.swing.JLabel();
        lblID = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblDetalleCompra = new javax.swing.JTable();
        jLabel9 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        txtBusqueda = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblInventario = new javax.swing.JTable();
        jLabel10 = new javax.swing.JLabel();
        txtCantidad = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txtPrecio = new javax.swing.JTextField();
        btnAgregar = new javax.swing.JButton();
        jLabel17 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        lblTotal = new javax.swing.JLabel();
        btnGuardar = new javax.swing.JButton();
        lblee = new javax.swing.JLabel();
        btnDelete = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        txtNumeroFactura = new javax.swing.JFormattedTextField();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "ID", "Nombre Producto", "Cantidad", "Precio", "Total"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("COMPRA DE MATERIA PRIMA");
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 153, 0));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnBuscar.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });
        jPanel1.add(btnBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 250, 80, -1));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setText("COMPRA DE MATERIA PRIMA");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 10, 334, -1));

        jLabel2.setText("Numero de Compra");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 153, -1));

        lblId.setText("1");
        lblId.setName("lbl_id"); // NOI18N
        jPanel1.add(lblId, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 70, 160, -1));

        jLabel4.setText("Fecha de la Compra");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 153, -1));

        jLabel5.setText("Fecha de Registro de la Compra");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, -1, -1));

        jLabel6.setText("Numero de Factura");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, 153, -1));

        jLabel7.setText("Proveedor");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 260, 153, -1));

        txtFechaCompra.setDateFormatString("yyyy-MM-dd");
        txtFechaCompra.setMaxSelectableDate(new Date());
        txtFechaCompra.setName("txt_fecha"); // NOI18N
        jPanel1.add(txtFechaCompra, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 110, 260, -1));
        jPanel1.add(lblFechaRegistro, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 160, 240, -1));
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(1100, 130, 10, 10));

        jPanel2.setLayout(null);

        lblNombre.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblNombre.setText("Nombre");
        jPanel2.add(lblNombre);
        lblNombre.setBounds(50, 10, 100, 14);

        lblTelefono.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblTelefono.setText("Telefono");
        jPanel2.add(lblTelefono);
        lblTelefono.setBounds(150, 10, 80, 14);

        lblEmail.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblEmail.setText("Email");
        jPanel2.add(lblEmail);
        lblEmail.setBounds(230, 10, 190, 14);

        lblRTN.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblRTN.setText("RTN");
        jPanel2.add(lblRTN);
        lblRTN.setBounds(430, 10, 140, 14);

        lblID.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblID.setText("ID");
        jPanel2.add(lblID);
        lblID.setBounds(10, 10, 30, 14);

        tblDetalleCompra.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Nombre", "Id Producto", "Cantidad", "Precio", "Total"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, true, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(tblDetalleCompra);
        if (tblDetalleCompra.getColumnModel().getColumnCount() > 0) {
            tblDetalleCompra.getColumnModel().getColumn(0).setResizable(false);
            tblDetalleCompra.getColumnModel().getColumn(2).setResizable(false);
            tblDetalleCompra.getColumnModel().getColumn(3).setResizable(false);
            tblDetalleCompra.getColumnModel().getColumn(4).setResizable(false);
            tblDetalleCompra.getColumnModel().getColumn(5).setResizable(false);
        }

        jPanel2.add(jScrollPane3);
        jScrollPane3.setBounds(10, 40, 560, 230);

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 60, 580, 280));
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 600, 10, 10));

        jPanel3.setLayout(null);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText("Buscar Producto");
        jPanel3.add(jLabel3);
        jLabel3.setBounds(90, 10, 110, 30);

        txtBusqueda.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtBusquedaKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtBusquedaKeyTyped(evt);
            }
        });
        jPanel3.add(txtBusqueda);
        txtBusqueda.setBounds(200, 10, 180, 30);

        tblInventario.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null}
            },
            new String [] {
                "ID", "Marca", "Unidad de Medida", "Nombre", "Existencia"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tblInventario);
        if (tblInventario.getColumnModel().getColumnCount() > 0) {
            tblInventario.getColumnModel().getColumn(0).setResizable(false);
            tblInventario.getColumnModel().getColumn(1).setResizable(false);
            tblInventario.getColumnModel().getColumn(2).setResizable(false);
            tblInventario.getColumnModel().getColumn(3).setResizable(false);
            tblInventario.getColumnModel().getColumn(4).setResizable(false);
        }

        jPanel3.add(jScrollPane2);
        jScrollPane2.setBounds(10, 50, 470, 180);

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel10.setText("Cantidad");
        jPanel3.add(jLabel10);
        jLabel10.setBounds(40, 240, 60, 30);

        txtCantidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCantidadActionPerformed(evt);
            }
        });
        txtCantidad.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCantidadKeyTyped(evt);
            }
        });
        jPanel3.add(txtCantidad);
        txtCantidad.setBounds(100, 240, 60, 30);

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel11.setText("Precio de Compra");
        jPanel3.add(jLabel11);
        jLabel11.setBounds(190, 240, 110, 30);

        txtPrecio.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtPrecio.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtPrecioKeyTyped(evt);
            }
        });
        jPanel3.add(txtPrecio);
        txtPrecio.setBounds(320, 240, 60, 30);

        btnAgregar.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnAgregar.setText("Agregar");
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });
        jPanel3.add(btnAgregar);
        btnAgregar.setBounds(390, 240, 80, 30);

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel17.setText("L.");
        jPanel3.add(jLabel17);
        jLabel17.setBounds(300, 250, 20, 20);

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 310, 490, 280));

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel16.setText("Total");
        jPanel1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 400, 80, 20));

        lblTotal.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jPanel1.add(lblTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 400, 80, 20));

        btnGuardar.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });
        jPanel1.add(btnGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 480, 110, 40));
        jPanel1.add(lblee, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 600, -1, -1));

        btnDelete.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnDelete.setForeground(new java.awt.Color(255, 0, 0));
        btnDelete.setText("X");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });
        jPanel1.add(btnDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(1050, 30, -1, -1));

        btnCancelar.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });
        jPanel1.add(btnCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 480, 110, 40));

        try {
            txtNumeroFactura.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###-###-##-########")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtNumeroFactura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNumeroFacturaActionPerformed(evt);
            }
        });
        jPanel1.add(txtNumeroFactura, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 190, 260, -1));

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
       MostrarProveedores p = new MostrarProveedores();
       p.setVisible(true);
       p.lblValor.setText("0");
        // TODO add your handling code here:
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void txtCantidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCantidadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCantidadActionPerformed

    int idd = 1;
    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
       if(txtNumeroFactura.getText().compareTo("")==0 && txtFechaCompra.getDate() == null){
           JOptionPane.showMessageDialog(rootPane, "Ingrese la fecha de la compra y el numero de la factura", "Advertencia", JOptionPane.ERROR_MESSAGE);
       }else if(txtNumeroFactura.getText().equals("   -   -  -        ")) {
                JOptionPane.showMessageDialog(rootPane, "Ingrese el numero de la factura", "Advertencia", JOptionPane.ERROR_MESSAGE);
       }else if(txtFechaCompra.getDate() == null){
          JOptionPane.showMessageDialog(rootPane, "Seleccione la fecha de la compra", "Advertencia", JOptionPane.ERROR_MESSAGE); 
       }else{
        if((lblID.getText()) == "ID" ){
           	JOptionPane.showMessageDialog(rootPane, "Seleccione un proveedor", "Advertencia", JOptionPane.ERROR_MESSAGE);
       }else{
        int fila = tblInventario.getSelectedRow();
        String id;
        if(fila >= 0 ){
        if (String.valueOf(txtCantidad.getText()).compareTo("") == 0
						&& String.valueOf(txtPrecio.getText()).compareTo("") == 0) {
					JOptionPane.showMessageDialog(rootPane, "Ingrese la cantidad y el precio del producto", "Advertencia", JOptionPane.ERROR_MESSAGE);
				}
				else if (String.valueOf(txtCantidad.getText()).compareTo(txtCantidad.getText()) == 0
						&& String.valueOf(txtPrecio.getText()).compareTo("") == 0) {
					JOptionPane.showMessageDialog(rootPane, "Ingrese el precio del producto", "Advertencia", JOptionPane.ERROR_MESSAGE);
				}

				else if (String.valueOf(txtCantidad.getText()).compareTo("") == 0
						&& String.valueOf(txtPrecio.getText()).compareTo(txtPrecio.getText()) == 0) {
					JOptionPane.showMessageDialog(rootPane, "Ingrese la cantidad de producto", "Advertencia", JOptionPane.ERROR_MESSAGE);
				}else{
                                    String Id, Marca, Unidad, Nombre, Existencia;
                                    int a=0;
                                    
                                    int filaa = tblInventario.getSelectedRow();
                                    
                                    Id= tblInventario.getValueAt(filaa, 0).toString();
                                    Marca= tblInventario.getValueAt(filaa, 1).toString();
                                    Nombre= tblInventario.getValueAt(filaa, 3).toString();
                                    Unidad= tblInventario.getValueAt(filaa, 2).toString();
                                    Existencia= tblInventario.getValueAt(filaa, 4).toString();
                                    
                                    for (int j = 0; j < tblDetalleCompra.getRowCount(); j++) {
                                        if (tblDetalleCompra.getValueAt(j, 2).toString().equals(Id)) {
                                            a++;
                                            
                                            
                                        }
                
            }
                                    if (a>0) {
                                        JOptionPane.showMessageDialog(rootPane, "Este producto ya fue registrado", "Advertencia", JOptionPane.ERROR_MESSAGE);
                
            } else {
                                        
                                       String xd = String.valueOf(idd);
                                       double Q = Double.parseDouble(txtCantidad.getText());
                                       String Cantidad = String.valueOf(Q);
                                       double P = Double.parseDouble(txtPrecio.getText());
                                       String Precio = String.valueOf(P);
                                       double calculo = Q*P;
                                       String Total = String.valueOf(calculo);
                                       
                                       DefaultTableModel m = (DefaultTableModel) tblDetalleCompra.getModel();
                                       
                                       String datos[] = {xd, Nombre, Id, Cantidad, Precio, Total};
                                       m.addRow(datos);
                                       idd++;
                                       
                                       subTotal = subTotal + calculo;
                                       lblTotal.setText(String.valueOf(subTotal));
                                       
                                       
                                       txtPrecio.setText("");
                                       txtCantidad.setText("");                                       
                                       
            }
                                }
        }
        }
       }
    
// TODO add your handling code here:
    }//GEN-LAST:event_btnAgregarActionPerformed

   
    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed

        
        Sentencias_Henry s = new Sentencias_Henry();
        s.setId_CM(Integer.parseInt(this.lblId.getText()));
        s.setFecha_CM(((JTextField)this.txtFechaCompra.getDateEditor().getUiComponent()).getText());
        s.setFecha_Regis_CM(this.lblFechaRegistro.getText());
        s.setNo_Factura_CM(this.txtNumeroFactura.getText());
        s.setFK_Id_Pro(Integer.parseInt(this.lblID.getText()));
        Funciones_Henry.isRegisterCompra(s);
        
        for (int i = 0; i < tblDetalleCompra.getRowCount(); i++) {
            s.setId_DE(Integer.parseInt(tblDetalleCompra.getValueAt(i, 0).toString()));
            s.setFK_Id_IMP(Integer.parseInt(tblDetalleCompra.getValueAt(i, 2).toString()));
            
            s.setId_IMP(Integer.parseInt(tblDetalleCompra.getValueAt(i, 2).toString()));
            Funciones_Henry.isUpdateInventario(s);
            
            s.setCantidad_DE(Double.parseDouble(tblDetalleCompra.getValueAt(i, 3).toString()));
            
            double e = s.getExistencia_IMP();
//            //JOptionPane.showMessageDialog(null, e);
//          
           double q = Double.parseDouble(tblDetalleCompra.getValueAt(i, 3).toString());
           double Total = e+q;
            
            s.setPrecio_DE(Double.parseDouble(tblDetalleCompra.getValueAt(i, 4).toString()));
            s.setTotal_DE(Double.parseDouble(tblDetalleCompra.getValueAt(i, 5).toString()));
            s.setFK_Id_CM(Integer.parseInt(this.lblId.getText()));
            s.setExistencia_IMP(Total);
            
            Funciones_Henry.isUpdateInventa(s);
            Funciones_Henry.isRegisterDetalleCompra(s);
            Funciones_Henry.setListarCompras("");
            JOptionPane.showMessageDialog(null, "Compra Registrada Con Exito");
            this.dispose();
            //JOptionPane.showMessageDialog(null, "Nueva Compra Registrada");
        }
// TODO add your handling code here:
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
       
       int r;
				r = JOptionPane.showConfirmDialog(this, "¿Desea quitar este producto de la compra?",
						"Confirmación", JOptionPane.OK_CANCEL_OPTION);
				if (r == JOptionPane.OK_OPTION) {
		 			double valor = Double.parseDouble(tblDetalleCompra.getValueAt(tblDetalleCompra.getSelectedRow(), 5).toString());
        subTotal = subTotal - valor;
        lblTotal.setText(String.valueOf(subTotal));
        
       DefaultTableModel m = (DefaultTableModel) tblDetalleCompra.getModel();
       int filla = tblDetalleCompra.getSelectedRow();
       m.removeRow(filla);
			}       
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
      int r;
                     r = JOptionPane.showConfirmDialog(this, "¿Desea Cancelar el Registro de la compra?",
						"Confirmación", JOptionPane.OK_CANCEL_OPTION);
				if (r == JOptionPane.OK_OPTION) {
		 			this.dispose();
			}        
// TODO add your handling code here:
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void txtNumeroFacturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNumeroFacturaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNumeroFacturaActionPerformed

    private void txtBusquedaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBusquedaKeyReleased
           Funciones_Henry.setListarInventario(txtBusqueda.getText());
          // TODO add your handling code here:
    }//GEN-LAST:event_txtBusquedaKeyReleased

    private void txtCantidadKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCantidadKeyTyped

        txtCantidad.setText(txtCantidad.getText().replaceAll("( )+", " "));
        if (txtCantidad.getText().length()==0 && evt.getKeyChar()==KeyEvent.VK_SPACE) {
            evt.consume();
        }
        char c = evt.getKeyChar();
        if(c<'0' || c>'9') evt.consume();      
        
        int tam = txtCantidad.getText().length();
        if(tam>=3){
            evt.consume();
        }         // TODO add your handling code here:
    }//GEN-LAST:event_txtCantidadKeyTyped

    private void txtPrecioKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPrecioKeyTyped
txtPrecio.setText(txtPrecio.getText().replaceAll("( )+", " "));
        if (txtPrecio.getText().length()==0 && evt.getKeyChar()==KeyEvent.VK_SPACE) {
            evt.consume();
        }
        char c = evt.getKeyChar();
        if(c<'0' || c>'9') evt.consume();      
        
        int tam = txtPrecio.getText().length();
        if(tam>=3){
            evt.consume();
        }         // TODO add your handling code here:
    }//GEN-LAST:event_txtPrecioKeyTyped

    private void txtBusquedaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBusquedaKeyTyped
        // TODO add your handling code here:
        txtBusqueda.setText(txtBusqueda.getText().replaceAll("( )+", " "));
        if (txtBusqueda.getText().length()==0 && evt.getKeyChar()==KeyEvent.VK_SPACE) {
            evt.consume();
        }
    }//GEN-LAST:event_txtBusquedaKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(COMPRA_MATERIA_PRIMA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(COMPRA_MATERIA_PRIMA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(COMPRA_MATERIA_PRIMA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(COMPRA_MATERIA_PRIMA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new COMPRA_MATERIA_PRIMA().setVisible(true);
            }
        });
    }
public int i=0; 
public double subTotal=0.00;
public double totalF=0.00;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable1;
    public static javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblFechaRegistro;
    public static javax.swing.JLabel lblID;
    private javax.swing.JLabel lblId;
    public static javax.swing.JLabel lblNombre;
    public static javax.swing.JLabel lblRTN;
    public static javax.swing.JLabel lblTelefono;
    private javax.swing.JLabel lblTotal;
    private javax.swing.JLabel lblee;
    public static javax.swing.JTable tblDetalleCompra;
    public static javax.swing.JTable tblInventario;
    private javax.swing.JTextField txtBusqueda;
    private javax.swing.JTextField txtCantidad;
    private com.toedter.calendar.JDateChooser txtFechaCompra;
    public static javax.swing.JFormattedTextField txtNumeroFactura;
    private javax.swing.JTextField txtPrecio;
    // End of variables declaration//GEN-END:variables
}