/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyectomp;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import static proyectomp.COMPRA_MATERIA_PRIMA.tblDetalleCompra;
import static proyectomp.MOSTRARCARGO.tblCa;

/**
 *
 * @author Calix
 */
public class DETALLE_PLANILLAS extends javax.swing.JFrame {

    /**
     * Creates new form DETALLE_PLANILLAS
     */
    public DETALLE_PLANILLAS() {
        initComponents();
        lblIdD.setText(Funciones.extraerIdMaxPlanillaDe());
        this.setLocationRelativeTo(null);
        tblBoni.getTableHeader().setReorderingAllowed(false);
        tbldedu.getTableHeader().setReorderingAllowed(false);
        tblMostrarEmp.getTableHeader().setReorderingAllowed(false);
                tblBoni.setSelectionMode(NORMAL);
        tbldedu.setSelectionMode(NORMAL);
        tblMostrarEmp.setSelectionMode(NORMAL);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        lblttl = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblMostrarEmp = new javax.swing.JTable();
        jButton5 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lblxxx = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        tbldedu = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblBoni = new javax.swing.JTable();
        lblNombre = new javax.swing.JLabel();
        lblApellido = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        lblId = new javax.swing.JLabel();
        btnDeleteDedus = new javax.swing.JButton();
        btnDeleteBoni = new javax.swing.JButton();
        lblSue = new javax.swing.JLabel();
        lblCa = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        lblTotalBoni = new javax.swing.JLabel();
        lblTotal = new javax.swing.JLabel();
        lblPago = new javax.swing.JLabel();
        btnAgregar = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        lblIdD = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        pagoooo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                formFocusLost(evt);
            }
        });
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                formMouseExited(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblttl.setText("0");
        jPanel1.add(lblttl, new org.netbeans.lib.awtextra.AbsoluteConstraints(1150, 650, 100, -1));

        tblMostrarEmp.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Empleado", "Apellido", "Cargo", "Sueldo", "Bonificacion", "Deduccion", "Total"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tblMostrarEmp);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 420, 1130, 210));

        jButton5.setText("BUSCAR");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 170, -1, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setText("Total Planilla");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(979, 650, 90, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("Seleccione un empleado");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 170, -1, -1));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setText("DETALLE PLANILLA");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(612, 11, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Id ");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(144, 65, -1, -1));

        lblxxx.setText("1");
        jPanel1.add(lblxxx, new org.netbeans.lib.awtextra.AbsoluteConstraints(402, 68, 130, -1));

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel10.setText("Deducciones");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 220, -1, -1));

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel12.setText("Bonificaciones");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 270, -1, -1));

        jPanel2.setBackground(new java.awt.Color(255, 204, 204));

        tbldedu.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Nombre", "Valor"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane4.setViewportView(tbldedu);
        if (tbldedu.getColumnModel().getColumnCount() > 0) {
            tbldedu.getColumnModel().getColumn(2).setResizable(false);
        }

        tblBoni.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Nombre", "Valor"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(tblBoni);

        jLabel8.setText("DEDUCCIONES");

        jLabel9.setText("BONIFICACIONES");

        lblId.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                lblIdKeyReleased(evt);
            }
        });

        btnDeleteDedus.setText("ELIMINAR");
        btnDeleteDedus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteDedusActionPerformed(evt);
            }
        });

        btnDeleteBoni.setText("ELIMINAR");
        btnDeleteBoni.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteBoniActionPerformed(evt);
            }
        });

        jLabel5.setText("Total a Pagar");

        lblTotalBoni.setText("0");

        lblTotal.setText("0");

        lblPago.setText("0");

        btnAgregar.setText("AGREGAR");
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel9)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(lblId, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lblNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lblApellido, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lblSue, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, Short.MAX_VALUE)
                        .addComponent(lblCa, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addGap(18, 18, 18)
                                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnDeleteBoni)
                                    .addComponent(btnDeleteDedus)))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(18, 18, 18)
                                .addComponent(lblPago, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 59, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addComponent(lblTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(172, 172, 172))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addComponent(btnAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(245, 245, 245))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addComponent(lblTotalBoni, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(115, 115, 115))))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(65, 65, 65)
                        .addComponent(btnDeleteDedus))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblNombre, javax.swing.GroupLayout.DEFAULT_SIZE, 14, Short.MAX_VALUE)
                            .addComponent(lblApellido, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblSue, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblCa, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblId, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblTotal)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addComponent(btnDeleteBoni))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblTotalBoni)
                .addGap(21, 21, 21)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(lblPago))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)
                .addComponent(btnAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 60, 710, 330));

        jButton3.setText("BUSCAR");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 220, -1, -1));

        jButton4.setText("BUSCAR");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 270, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Id_Planilla");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(144, 116, -1, -1));

        lblIdD.setText("1");
        jPanel1.add(lblIdD, new org.netbeans.lib.awtextra.AbsoluteConstraints(402, 119, 50, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/fondo2.jpg"))); // NOI18N
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1400, 940));

        pagoooo.setText("jLabel4");
        jPanel1.add(pagoooo, new org.netbeans.lib.awtextra.AbsoluteConstraints(47, 451, -1, -1));

        jScrollPane1.setViewportView(jPanel1);

        getContentPane().add(jScrollPane1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
        Funciones.setListarDetalle(lblIdD.getText());  
        int a =0;
        for(int i=0; i< tblMostrarEmp.getRowCount(); i++){
            if(tblMostrarEmp.getValueAt(i,0).toString().equals(lblId.getText())){
                a+=1;
              //JOptionPane.showMessageDialog(null, "Ya esta registrado");
            }
        }
        if(a>0){
             JOptionPane.showMessageDialog(null, "Ya esta registrado");
           

        }else{
       Sentencias s = new Sentencias();
       
       s.setFK_Empleado(Integer.parseInt(this.lblId.getText()));
       s.setFK_Planilla(Integer.parseInt(this.lblIdD.getText()));
       s.setTotal_A_Pagar(Double.parseDouble(this.lblPago.getText()));
       s.setTotalBoni(Double.parseDouble(this.lblTotalBoni.getText()));
       s.setTotalDedu(Double.parseDouble(this.lblTotal.getText()));
       
       
        if (Funciones.isRegisterDEP(s)) {
            JOptionPane.showMessageDialog(this, "DETALLE DE PLANILLA A SIDO CREADO");
            Funciones.setListarDetalle(lblIdD.getText());
            Funciones.sumarPLANILLA();
            Funciones.setListarJoinPLANILLA();
            Funciones.eliminar();
            Funciones.eliminarD();
            limpiar();
            //Funciones.setListarJoinPLANILLA();
            
            
            }else{
                JOptionPane.showMessageDialog(this, "No se pudo realizar la operacion");
                
            }
            
        }
      //  dispose();
    }//GEN-LAST:event_btnAgregarActionPerformed

    private void limpiar(){
        //JOptionPane.showMessageDialog(null, "Ya esta registrado");
             DefaultTableModel modelo = (DefaultTableModel)this.tbldedu.getModel();
             while(modelo.getRowCount() > 0 ){
                modelo.removeRow(0);
                
            }
              DefaultTableModel modelo1 = (DefaultTableModel)this.tblBoni.getModel();
             while(modelo1.getRowCount() > 0 ){
                modelo1.removeRow(0);
                
            }
             lblId.setText("");
             lblCa.setText("");
             lblApellido.setText("");
             lblNombre.setText("");
             lblSue.setText("");
             lblTotal.setText("0");
             lblTotalBoni.setText("0");
             lblPago.setText("0");
        
    
}
    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed

        if(lblId.getText().length()==0 || 
                
                this.lblNombre.getText().length()==0){
            JOptionPane.showMessageDialog(null, "Debe seleccionar un empleado");
        }else{ 
        SELECCIONAR_DEDUCCION S = new SELECCIONAR_DEDUCCION();
        SELECCIONAR_DEDUCCION.lbl.setText(this.lblId.getText());
        SELECCIONAR_DEDUCCION.pagooo.setText(this.pagoooo.getText());
        SELECCIONAR_DEDUCCION.idPlanilla.setText(this.lblIdD.getText());
       S.setVisible(true);
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void lblIdKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_lblIdKeyReleased
      
    }//GEN-LAST:event_lblIdKeyReleased

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        if(lblId.getText().length()==0 || 
                
                this.lblNombre.getText().length()==0){
            JOptionPane.showMessageDialog(null, "Debe seleccionar un empleado");
        }else{  
        Seleccionar_Bonificacioin S = new Seleccionar_Bonificacioin();
        Seleccionar_Bonificacioin.LBLEMP.setText(this.lblId.getText());
         Seleccionar_Bonificacioin.pagooo.setText(this.pagoooo.getText());
        Seleccionar_Bonificacioin.idPlanilla.setText(this.lblIdD.getText());
       S.setVisible(true);
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
       MostarEmpleadosPlanilla M = new MostarEmpleadosPlanilla();
       M.setVisible(true);
    }//GEN-LAST:event_jButton5ActionPerformed

    private void btnDeleteDedusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteDedusActionPerformed
        int fila = tbldedu.getSelectedRow();
        DefaultTableModel m = (DefaultTableModel) tbldedu.getModel();
       m.removeRow(fila);
        
//        Sentencias s = new Sentencias();
//        s.setId_Egr(Integer.parseInt(lblIdD.getText()));
//        s.setFK_Empleado(Integer.parseInt(lblId.getText()));
//        s.setFK_Planilla(Integer.parseInt(tbldedu.getValueAt(fila, 0).toString()));
//        if(Funciones.Delete_dedu_planilla_U(s)){
//            JOptionPane.showMessageDialog(null, "Deduccion eliminado correctamente");
//            Funciones.setListarJoinDedu(lblId.getText(), lblIdD.getText());
           Funciones.sumarColumn();
           Funciones.sumarTotalAPagar();
//            
//        }
        
        
    }//GEN-LAST:event_btnDeleteDedusActionPerformed

    private void btnDeleteBoniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteBoniActionPerformed
        int fila = tblBoni.getSelectedRow();
        DefaultTableModel m = (DefaultTableModel) tblBoni.getModel();
       m.removeRow(fila);
//        Sentencias s = new Sentencias();
//        s.setId_Boni(Integer.parseInt(lblIdD.getText()));
//        s.setFK_Empleado(Integer.parseInt(lblId.getText()));
//        s.setFK_Planilla(Integer.parseInt(tblBoni.getValueAt(fila, 0).toString()));
//        if(Funciones.Delete_boni_planilla_U(s)){
//            JOptionPane.showMessageDialog(null, "Bonificacion eliminado correctamente");
//            Funciones.setListarJoinBoni(lblId.getText(), lblIdD.getText());
            Funciones.sumarColumnBoni();
           Funciones.sumarTotalAPagar();
//            
//        }  
    }//GEN-LAST:event_btnDeleteBoniActionPerformed

    private void formFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_formFocusLost

    }//GEN-LAST:event_formFocusLost

    private void formMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseExited

    }//GEN-LAST:event_formMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DETALLE_PLANILLAS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DETALLE_PLANILLAS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DETALLE_PLANILLAS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DETALLE_PLANILLAS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DETALLE_PLANILLAS().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnDeleteBoni;
    private javax.swing.JButton btnDeleteDedus;
    public static javax.swing.JButton jButton3;
    public static javax.swing.JButton jButton4;
    public static javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    public static javax.swing.JLabel lblApellido;
    public static javax.swing.JLabel lblCa;
    public static javax.swing.JLabel lblId;
    public static javax.swing.JLabel lblIdD;
    public static javax.swing.JLabel lblNombre;
    public static javax.swing.JLabel lblPago;
    public static javax.swing.JLabel lblSue;
    public static javax.swing.JLabel lblTotal;
    public static javax.swing.JLabel lblTotalBoni;
    public static javax.swing.JLabel lblttl;
    private javax.swing.JLabel lblxxx;
    public static javax.swing.JLabel pagoooo;
    public static javax.swing.JTable tblBoni;
    public static javax.swing.JTable tblMostrarEmp;
    public static javax.swing.JTable tbldedu;
    // End of variables declaration//GEN-END:variables
}
