/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyectomp;

import static com.lowagie.text.pdf.codec.BmpImage.getImage;
import java.awt.Image;
import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import static javax.swing.UIManager.getIcon;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.table.DefaultTableModel;
import net.sf.jasperreports.engine.JRException;
import static proyectomp.EMPLEADOSS_Update.cargarFoto;
import static proyectomp.EMPLEADOSS_Update.url;
import static proyectomp.Mostrar_Clientes.jTable1;
import Reportes.Reportes;
import java.awt.Event;
import java.awt.event.KeyEvent;
import javax.swing.InputMap;
import javax.swing.KeyStroke;
import static proyectomp.EMPLEADOSS_Update.oculto;

/**
 *
 * @author Calix
 */
public class EMPLEADOS extends javax.swing.JFrame {

    DefaultTableModel dtm = new DefaultTableModel();
    private Object calendarNac;
    
    /**
     * Creates new form EMPLEADOS
     */
    public EMPLEADOS() {
        initComponents();
       this.setResizable(false);
       tblTabla.getTableHeader().setReorderingAllowed(false);
       tblTabla.setSelectionMode(NORMAL);
       InputMap map3 = txtBuscar.getInputMap(JTextField.WHEN_FOCUSED); 
    map3.put(KeyStroke.getKeyStroke(KeyEvent.VK_V, Event.CTRL_MASK), "null");
    
    
       
         Funciones_Angel.setListar_EM("");
         
        
 
       String[] tituloTabla=new String[]
        {"Id_E", "Nombres_E", "Apellidos_E", "Identidad_E", "Telefono_E", "Direccion_E", "Genero_E", "Tipo_Contrato_E", "Estado_E",
                "Referencia_E", "Telefono_Referencia_E", "Fecha_Nac_E", "Fecha_Reg_E", "Fecha_Inicio_E"};
        
      
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel = new javax.swing.JPanel();
        btnImprmir = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblTabla = new javax.swing.JTable();
        lblEmp = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        txtBuscar = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setExtendedState(6);
        setResizable(false);

        panel.setBackground(new java.awt.Color(255, 255, 255));
        panel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnImprmir.setText("IMPRIMIR");
        btnImprmir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnImprmirActionPerformed(evt);
            }
        });
        panel.add(btnImprmir, new org.netbeans.lib.awtextra.AbsoluteConstraints(1130, 590, 140, 60));

        tblTabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Id", "Nombres", "Apellidos", "Identidad", "Telefono", "Direccion", "Genero", "Tipo de Contrato", "Estado", "Referencia", "Telefono de Referencia", "Fecha de Nacimiento", "Fecha de Registro", "Fecha de Inicio", "Id Cargo", "url", "TipoCargo", "Title 18", "Title 19"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblTabla);
        if (tblTabla.getColumnModel().getColumnCount() > 0) {
            tblTabla.getColumnModel().getColumn(14).setMinWidth(0);
            tblTabla.getColumnModel().getColumn(14).setPreferredWidth(0);
            tblTabla.getColumnModel().getColumn(14).setMaxWidth(0);
            tblTabla.getColumnModel().getColumn(15).setMinWidth(0);
            tblTabla.getColumnModel().getColumn(15).setPreferredWidth(0);
            tblTabla.getColumnModel().getColumn(15).setMaxWidth(0);
            tblTabla.getColumnModel().getColumn(16).setMinWidth(0);
            tblTabla.getColumnModel().getColumn(16).setPreferredWidth(0);
            tblTabla.getColumnModel().getColumn(16).setMaxWidth(0);
            tblTabla.getColumnModel().getColumn(17).setMinWidth(0);
            tblTabla.getColumnModel().getColumn(17).setPreferredWidth(0);
            tblTabla.getColumnModel().getColumn(17).setMaxWidth(0);
        }

        panel.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 87, 1336, 473));

        lblEmp.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lblEmp.setText("Empleados");
        panel.add(lblEmp, new org.netbeans.lib.awtextra.AbsoluteConstraints(673, 11, 133, 27));

        jLabel1.setText("Buscar por:");
        panel.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(996, 47, -1, -1));

        txtBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBuscarActionPerformed(evt);
            }
        });
        txtBuscar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtBuscarKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtBuscarKeyTyped(evt);
            }
        });
        panel.add(txtBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(1090, 40, 190, -1));

        jButton1.setText("REGISTRAR");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        panel.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(66, 593, 132, 65));

        jButton2.setText("ACTUALIZAR");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        panel.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 590, 123, 66));

        jButton3.setText("BORRAR");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        panel.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 591, 147, 60));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/fondo2.jpg"))); // NOI18N
        panel.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1360, 670));

        getContentPane().add(panel, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        EMPLEADOSS_CREAR E = new EMPLEADOSS_CREAR();
            E.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
//        FileImputStream foto;
        
        int fila = tblTabla.getSelectedRow();
        
        if (tblTabla.getSelectedRow()==-1) {
            JOptionPane.showMessageDialog(null, "Debe seleccionar un campo a editar");
        }else{
            
        
        
        
        EMPLEADOSS_Update EU = new EMPLEADOSS_Update();
         EU.labelID.setText(tblTabla.getValueAt(fila, 0).toString());
       EU.txtNombre.setText(tblTabla.getValueAt(fila, 1).toString());
       EU.txtApell.setText(tblTabla.getValueAt(fila, 2).toString());
       EU.txtIden.setText(tblTabla.getValueAt(fila, 3).toString());
       EU.txtTele.setText(tblTabla.getValueAt(fila, 4).toString());
       EU.txareDirect.setText(tblTabla.getValueAt(fila, 5).toString());
       EU.combGen.setSelectedItem(tblTabla.getValueAt(fila, 6).toString());
       EU.comTipCont.setSelectedItem(tblTabla.getValueAt(fila, 7).toString());
       EU.combEstado.setSelectedItem(tblTabla.getValueAt(fila, 8).toString());
       EU.txtRef.setText(tblTabla.getValueAt(fila, 9).toString());
       EU.txtTelRef.setText(tblTabla.getValueAt(fila, 10).toString());
       //((JTextField)EU.calendarNac.getDateEditor()).setText(tblTabla.getValueAt(fila, 11).toString());
        ((JTextField)EU.jDateChooser1.getDateEditor()).setText(tblTabla.getValueAt(fila, 11).toString());
//       EU.calendarNac.setText(tblTabla.getValueAt(fila, 11).toString());
       EU.labefechReg.setText(tblTabla.getValueAt(fila, 12).toString());
//       EU.calendarInic.setText(tblTabla.getValueAt(fila, 13).toString());
       ((JTextField)EU.calendarInic.getDateEditor()).setText(tblTabla.getValueAt(fila, 13).toString());
      EU.oculto.setText(tblTabla.getValueAt(fila, 14).toString());
      Sentencias_Angel s = new Sentencias_Angel();
//        s.setFK_Id_ca(Integer.parseInt(tblTabla.getValueAt(fila, 14).toString()));
//        Funciones_Angel.setListarTipoCargo(s);
//        String n = s.getNom_ca();
//        EU.comboCargo.setSelectedItem(s.getNom_ca().toString());
//        JOptionPane.showMessageDialog(null, n);
      //EU.comboTipoCarg.setSelectedItem(tblTabla.getValueAt(fila, 17).toString());

EU.url.setText(tblTabla.getValueAt(fila, 15).toString());
try {
                ImageIcon ImgIcon = new ImageIcon(url.getText());
                Icon icono = new ImageIcon(ImgIcon.getImage().getScaledInstance(cargarFoto.getWidth(), cargarFoto.getHeight(), Image.SCALE_DEFAULT));
                cargarFoto.setIcon(icono);
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Error al abrir");
            }
     EU.comboTipoCarg.setSelectedItem(tblTabla.getValueAt(fila, 16).toString());
     EU.comboCargo.setSelectedItem(tblTabla.getValueAt(fila, 17).toString());
     if(tblTabla.getValueAt(fila, 18).toString().equals("1")){
           EU.CheckUsuario.setSelected(true);
       }
     
     

//       EU.calendarInic.setText(tblTabla.getValueAt(fila, 13).toString());
     //  EU.txtTele.setText(tblTabla.getValueAt(fila, 14).toString());
    
              EU.setVisible(true);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void txtBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBuscarActionPerformed
        // TODO add your handling code here:
        Funciones_Angel.setListar_EM(this.txtBuscar.getText());
    }//GEN-LAST:event_txtBuscarActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        if (tblTabla.getSelectedRow()==-1) {
            JOptionPane.showMessageDialog(null, "Debe seleccionar un campo a borrar");
        }else{
            int fila = tblTabla.getSelectedRow();
        
        Sentencias_Angel s = new Sentencias_Angel();
        s.setId_E(Integer.parseInt(tblTabla.getValueAt(fila, 0).toString()));
        s.setId_Usu(Integer.parseInt(tblTabla.getValueAt(fila, 0).toString()));
        
        int a= JOptionPane.showConfirmDialog(null, "esta seguro", "mostrar", JOptionPane.YES_NO_OPTION);
        if (a==JOptionPane.YES_NO_OPTION) {
            
        
        
        
        Funciones_Angel.isDeleteUsu(s);
        if(Funciones_Angel.isDelete_EM(s)){
            
            JOptionPane.showMessageDialog(this, "Empleado Eliminado");
            Funciones_Angel.setListar_EM("");
        }else{
            JOptionPane.showMessageDialog(this, "No se a podido eliminar");
            
            
        }
        }else{
            JOptionPane.showMessageDialog(null, "No se realizo el eliminado");
        }
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void btnImprmirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnImprmirActionPerformed
        
      try {
            Reportes reporte = new Reportes();
            reporte.ReporteEmpleados();
            
        } catch (JRException ex) {
            Logger.getLogger(Reportes.class.getName()).log(Level.SEVERE, null, ex);
        } catch(SQLException ex){
            Logger.getLogger(Reportes.class.getName()).log(Level.SEVERE, null, ex);
        }
// TODO add your handling code here:
    }//GEN-LAST:event_btnImprmirActionPerformed

    private void txtBuscarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBuscarKeyReleased
        Funciones_Angel.setListar_EM(this.txtBuscar.getText());
    }//GEN-LAST:event_txtBuscarKeyReleased

    private void txtBuscarKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBuscarKeyTyped
        // TODO add your handling code here:
        txtBuscar.setText(txtBuscar.getText().replaceAll("( )+", " "));
        if (txtBuscar.getText().length()==0 && evt.getKeyChar()==KeyEvent.VK_SPACE) {
            evt.consume();          
        }
    }//GEN-LAST:event_txtBuscarKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EMPLEADOS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EMPLEADOS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EMPLEADOS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EMPLEADOS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EMPLEADOS().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnImprmir;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    public static javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblEmp;
    private javax.swing.JPanel panel;
    public static javax.swing.JTable tblTabla;
    private javax.swing.JTextField txtBuscar;
    // End of variables declaration//GEN-END:variables
}
