/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyectomp;

import java.awt.Event;
import java.awt.event.KeyEvent;
import javax.swing.InputMap;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.KeyStroke;
import static proyectomp.Planilla_Update_2.observaciones;

/**
 *
 * @author angel
 */
public class Ingreso_Actualizar extends javax.swing.JFrame {

    /**
     * Creates new form Ingreso_Crear
     */
    public Ingreso_Actualizar() {
        initComponents();
        InputMap map3 = txArDescrip.getInputMap(JTextField.WHEN_FOCUSED); 
    map3.put(KeyStroke.getKeyStroke(KeyEvent.VK_V, Event.CTRL_MASK), "null");
    InputMap map4 = txtNombre.getInputMap(JTextField.WHEN_FOCUSED); 
    map4.put(KeyStroke.getKeyStroke(KeyEvent.VK_V, Event.CTRL_MASK), "null");
    InputMap map5 = txtMonto.getInputMap(JTextField.WHEN_FOCUSED); 
    map5.put(KeyStroke.getKeyStroke(KeyEvent.VK_V, Event.CTRL_MASK), "null");
    ((JTextField)calendarFechha.getDateEditor()).setEditable(false);
        txArDescrip.setLineWrap(true);
        this.setLocationRelativeTo(null);
        this.lblId.setText(Funciones_Angel.extraerIdMaxIng());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        guardar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        lblId = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        txtMonto = new javax.swing.JTextField();
        calendarFechha = new com.toedter.calendar.JDateChooser();
        jScrollPane1 = new javax.swing.JScrollPane();
        txArDescrip = new javax.swing.JTextArea();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        guardar.setText("ACTUALIZAR");
        guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guardarActionPerformed(evt);
            }
        });
        jPanel1.add(guardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 340, -1, -1));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setText("INGRESOS");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(193, 11, -1, 24));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("ID");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(53, 75, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Nombre");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(53, 110, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Monto");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(53, 148, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("Fecha");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(53, 183, -1, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("Descripción");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(53, 218, -1, -1));
        jPanel1.add(lblId, new org.netbeans.lib.awtextra.AbsoluteConstraints(155, 75, 164, 14));

        txtNombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNombreKeyTyped(evt);
            }
        });
        jPanel1.add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(155, 110, 233, -1));

        txtMonto.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtMonto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtMontoKeyTyped(evt);
            }
        });
        jPanel1.add(txtMonto, new org.netbeans.lib.awtextra.AbsoluteConstraints(155, 145, 233, -1));

        calendarFechha.setDateFormatString("yyy-MM-dd");
        jPanel1.add(calendarFechha, new org.netbeans.lib.awtextra.AbsoluteConstraints(155, 180, 233, -1));

        txArDescrip.setColumns(20);
        txArDescrip.setRows(5);
        txArDescrip.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txArDescripKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txArDescripKeyTyped(evt);
            }
        });
        jScrollPane1.setViewportView(txArDescrip);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(155, 218, 233, -1));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/fondo2.jpg"))); // NOI18N
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 480, 390));

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void guardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guardarActionPerformed
        // TODO add your handling code here:
        if(txtNombre.getText().length()==0 || 
                this.txtMonto.getText().length()==0||
//                this.calendarFechha.getDate().equals(null)||
                this.txArDescrip.getText().length()==0){
            JOptionPane.showMessageDialog(null, "Todo los campos son requeridos");
        }else{
            Sentencias_Angel s = new Sentencias_Angel();
            s.setId_Ing(Integer.parseInt(this.lblId.getText()));
            s.setNombre_Ing(this.txtNombre.getText());
            s.setMonto_Ing(Double.parseDouble(this.txtMonto.getText()));
            s.setFecha_Ing(((JTextField)this.calendarFechha.getDateEditor().getUiComponent()).getText());
            s.setDescripcion_Ing(this.txArDescrip.getText());
            
            
            if(Funciones_Angel.isUpdateIng(s)){
               // Funciones.setListar("");
            JOptionPane.showMessageDialog(this, "Ingreso Actualizado");
            Funciones_Angel.setListarIng("");
            
            }else{
                JOptionPane.showMessageDialog(this, "Fallo el Registro");
                
            }
            dispose();      
        }
    }//GEN-LAST:event_guardarActionPerformed

    private void txtNombreKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNombreKeyTyped
txtNombre.setText(txtNombre.getText().replaceAll("( )+", " "));
        if (txtNombre.getText().length()==0 && evt.getKeyChar()==KeyEvent.VK_SPACE) {
            evt.consume();
            
        } char c = evt.getKeyChar();
         if(Character.isDigit(c)){
            getToolkit().beep();
            evt.consume();
         }
            int tam = txtNombre.getText().length();
        if(tam>=30){
            evt.consume();
        }  else if((int)evt.getKeyChar()>32 && (int)evt.getKeyChar()<=47
                ||(int)evt.getKeyChar()>=58 && (int)evt.getKeyChar()<=64
                ||(int)evt.getKeyChar()>=91 && (int)evt.getKeyChar()<=96
                ||(int)evt.getKeyChar()>=123 && (int)evt.getKeyChar()<=163
                ||(int)evt.getKeyChar()>=166 && (int)evt.getKeyChar()<=255){
             getToolkit().beep();
            evt.consume();
        }        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreKeyTyped

    private void txtMontoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtMontoKeyTyped
char c = evt.getKeyChar();
        if(c<'0' || c>'9') evt.consume();      
        
        int tam = txtMonto.getText().length();
        if(tam>=6){
            evt.consume();
        }              // TODO add your handling code here:
    }//GEN-LAST:event_txtMontoKeyTyped

    private void txArDescripKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txArDescripKeyTyped
  txArDescrip.setText(txArDescrip.getText().replaceAll("( )+", " "));
        if (txArDescrip.getText().length()==0 && evt.getKeyChar()==KeyEvent.VK_SPACE) {
            evt.consume();
            
        }int tam = txArDescrip.getText().length();
        if(tam>=300){
            evt.consume();
       
        }
                 // TODO add your handling code here:
    }//GEN-LAST:event_txArDescripKeyTyped

    private void txArDescripKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txArDescripKeyPressed

        if (evt.getKeyCode() == KeyEvent.VK_TAB) {
                    if (evt.getModifiers() > 0) {
                        txArDescrip.transferFocusBackward();
                    } else {
                        txArDescrip.transferFocus();
                    }
                    evt.consume();  
        }// TODO add your handling code here:
    }//GEN-LAST:event_txArDescripKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ingreso_Actualizar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ingreso_Actualizar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ingreso_Actualizar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ingreso_Actualizar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ingreso_Actualizar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static com.toedter.calendar.JDateChooser calendarFechha;
    private javax.swing.JButton guardar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    public static javax.swing.JLabel lblId;
    public static javax.swing.JTextArea txArDescrip;
    public static javax.swing.JTextField txtMonto;
    public static javax.swing.JTextField txtNombre;
    // End of variables declaration//GEN-END:variables

    void txtNombre(String toString) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
