/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyectomp;

import Reportes.Reportes;
import java.awt.Event;
import java.awt.event.KeyEvent;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.InputMap;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.KeyStroke;
import net.sf.jasperreports.engine.JRException;
import static proyectomp.CARGOS_REGISTRO.txtFun;
import static proyectomp.CARGOS_UPDATE.TxtSue1;
import static proyectomp.CARGOS_UPDATE.txtFun;
import static proyectomp.CARGOS_UPDATE.txtNombre;
import static proyectomp.MOSTRARCARGO.tblCa;

/**
 *
 * @author Calix
 */
public class LOCAL_REGISTRO extends javax.swing.JFrame {

    /**
     * Creates new form Local
     */
    public LOCAL_REGISTRO() {
        initComponents();
        tblLocal.setSelectionMode(NORMAL);
        tblLocal.getTableHeader().setReorderingAllowed(false);
        this.setLocationRelativeTo(null);
        btnActualizar.setVisible(false);
         InputMap map2 = txtNombre.getInputMap(JTextField.WHEN_FOCUSED); 
    map2.put(KeyStroke.getKeyStroke(KeyEvent.VK_V, Event.CTRL_MASK), "null");
    
    
    InputMap maps = txtRTN.getInputMap(JTextField.WHEN_FOCUSED); 
    maps.put(KeyStroke.getKeyStroke(KeyEvent.VK_V, Event.CTRL_MASK), "null");
    
    InputMap map3 = txtTelefono.getInputMap(JTextField.WHEN_FOCUSED); 
    map3.put(KeyStroke.getKeyStroke(KeyEvent.VK_V, Event.CTRL_MASK), "null");
    
         InputMap map4 = txtDireccion.getInputMap(JTextField.WHEN_FOCUSED); 
    map4.put(KeyStroke.getKeyStroke(KeyEvent.VK_V, Event.CTRL_MASK), "null");

       
        txtDireccion.setLineWrap(true);
        lblId.setText(Funciones.extraerIdMaxLocal());
        Funciones.setListarLocal("");
    }
    
    private void clean(){
        txtNombre.setText("");
        txtDireccion.setText("");
        txtRTN.setText("");
        txtTelefono.setText("");
        txtTelefono2.setText("");
        txtNombre.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnimprimir = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        lblId = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtDireccion = new javax.swing.JTextArea();
        btnGuardar = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblLocal = new javax.swing.JTable();
        btnEditar = new javax.swing.JButton();
        btnBorarr = new javax.swing.JButton();
        btnActualizar = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        txtRTN = new javax.swing.JFormattedTextField();
        txtTelefono = new javax.swing.JFormattedTextField();
        txtTelefono2 = new javax.swing.JFormattedTextField();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnimprimir.setText("IMPRIMIR");
        btnimprimir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnimprimirActionPerformed(evt);
            }
        });
        jPanel1.add(btnimprimir, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 270, 100, 40));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setText("REGISTRO LOCAL");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(422, 14, -1, -1));

        jLabel2.setText("Id");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(44, 49, 37, -1));

        txtNombre.setNextFocusableComponent(txtRTN);
        txtNombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNombreKeyTyped(evt);
            }
        });
        jPanel1.add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(197, 81, 174, -1));

        lblId.setText("1");
        jPanel1.add(lblId, new org.netbeans.lib.awtextra.AbsoluteConstraints(197, 49, 62, -1));

        jLabel4.setText("Nombre");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(44, 84, -1, -1));

        jLabel5.setText("RTN");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(44, 122, -1, -1));

        jLabel6.setText("Telefono1");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(44, 153, -1, -1));

        jLabel7.setText("Telefono2");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(39, 205, -1, -1));

        jLabel8.setText("Direccion");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(39, 266, -1, -1));

        txtDireccion.setColumns(20);
        txtDireccion.setRows(5);
        txtDireccion.setNextFocusableComponent(txtNombre);
        txtDireccion.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtDireccionKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtDireccionKeyTyped(evt);
            }
        });
        jScrollPane1.setViewportView(txtDireccion);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(197, 266, -1, -1));

        btnGuardar.setText("GUARDAR");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });
        jPanel1.add(btnGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 420, -1, -1));

        tblLocal.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Id", "Nombre", "RTN", "Telefono", "Telefono2", "Direccion"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tblLocal);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 81, -1, 106));

        btnEditar.setText("EDITAR");
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });
        jPanel1.add(btnEditar, new org.netbeans.lib.awtextra.AbsoluteConstraints(593, 266, 109, 35));

        btnBorarr.setText("BORRAR");
        btnBorarr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBorarrActionPerformed(evt);
            }
        });
        jPanel1.add(btnBorarr, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 270, 111, 35));

        btnActualizar.setText("ACTUALIZAR");
        btnActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarActionPerformed(evt);
            }
        });
        jPanel1.add(btnActualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 420, -1, -1));

        jButton1.setText("LIMPIAR");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(118, 418, -1, -1));

        try {
            txtRTN.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("####-####-#####-#")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtRTN.setNextFocusableComponent(txtTelefono);
        jPanel1.add(txtRTN, new org.netbeans.lib.awtextra.AbsoluteConstraints(197, 119, 174, -1));

        try {
            txtTelefono.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtTelefono.setNextFocusableComponent(txtTelefono2);
        txtTelefono.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTelefonoActionPerformed(evt);
            }
        });
        jPanel1.add(txtTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(197, 150, 174, -1));

        try {
            txtTelefono2.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtTelefono2.setNextFocusableComponent(txtDireccion);
        jPanel1.add(txtTelefono2, new org.netbeans.lib.awtextra.AbsoluteConstraints(197, 205, 166, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/fondo2.jpg"))); // NOI18N
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, 450));

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
         if(txtNombre.getText().length()==0 || 
                this.txtNombre.getText().length()==0||
                this.txtDireccion.getText().length()==0||
                 this.txtTelefono.getText().equals("    -    ")||
                 this.txtTelefono2.getText().equals("    -    ")||
                this.txtRTN.getText().equals("    -    -     - ")){
            JOptionPane.showMessageDialog(null, "Todos los campos son requeridos");
        }else{
        Sentencias s = new Sentencias();
        s.setNombre_L(this.txtNombre.getText());
        s.setDireccion_L(this.txtDireccion.getText());
        s.setRTN_L(this.txtRTN.getText());
        s.setTelefono_L(this.txtTelefono.getText());
        s.setTelefono2_L(this.txtTelefono2.getText());
        
        
        if (Funciones.isRegisterLocal(s)) {
            JOptionPane.showMessageDialog(null, "REGISTRO EXITOSO", "FUNCIONO", WIDTH);
            clean();
           Funciones.setListarLocal("");
           lblId.setText(Funciones.extraerIdMaxLocal());
            
        } else {
            JOptionPane.showMessageDialog(null, "Fallo al Registrar", "ERROR", HEIGHT);
        }
         }
    }//GEN-LAST:event_btnGuardarActionPerformed
public void NoSpace(KeyEvent e, int tam){
    if (tam == 0 && e.getKeyChar() == KeyEvent.VK_SPACE) {
        e.consume();
    }
}
    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
        
        int fila = tblLocal.getSelectedRow();
        
        txtNombre.setText(tblLocal.getValueAt(fila, 1).toString());
        txtRTN.setText(tblLocal.getValueAt(fila, 2).toString());
        txtTelefono.setText(tblLocal.getValueAt(fila, 3).toString());
        txtTelefono2.setText(tblLocal.getValueAt(fila, 4).toString());
        lblId.setText(tblLocal.getValueAt(fila, 0).toString());
        txtDireccion.setText(tblLocal.getValueAt(fila, 5).toString());
        setVisible(true);
        btnGuardar.setVisible(false);
        btnActualizar.setVisible(true);
        
        
    }//GEN-LAST:event_btnEditarActionPerformed

    private void btnActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarActionPerformed
         if(txtNombre.getText().length()==0 || 
                this.txtNombre.getText().length()==0||
                this.txtDireccion.getText().length()==0||
                 this.txtTelefono.getText().equals("    -    ")||
                 this.txtTelefono2.getText().equals("    -    ")||
                this.txtRTN.getText().equals("    -    -     - ")){
            JOptionPane.showMessageDialog(null, "Todos los campos son requeridos");
        }else{
        Sentencias s = new Sentencias();
        
        s.setNombre_L(this.txtNombre.getText());
        s.setRTN_L(this.txtRTN.getText());
        s.setTelefono_L(this.txtTelefono.getText());
        s.setTelefono2_L(this.txtTelefono2.getText());
        s.setDireccion_L(this.txtDireccion.getText());
        s.setId_L(Integer.parseInt(this.lblId.getText()));
        
        if (Funciones.isUpdateLocal(s)) {
            JOptionPane.showMessageDialog(null, "Actualizacion Exitosa");
            Funciones.setListarLocal("");
            lblId.setText(Funciones.extraerIdMaxLocal());
            btnGuardar.setVisible(true);
            btnActualizar.setVisible(false);
            clean();
            
        } else {
            JOptionPane.showMessageDialog(null, "Error al Actualizar");
        }
         }
        
    }//GEN-LAST:event_btnActualizarActionPerformed

    private void btnBorarrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBorarrActionPerformed
        // TODO add your handling code here:
        if (tblLocal.getSelectedRow()==-1) {
            JOptionPane.showMessageDialog(null, "Debe seleccionar un campo a editar");
        }else{
        int fila = tblLocal.getSelectedRow();
        Sentencias s = new Sentencias();
       s.setId_L(Integer.parseInt(tblLocal.getValueAt(fila, 0).toString()));
           int f = JOptionPane.showConfirmDialog(null, "Desea Eliminar este Registro?", "Eliminar", WIDTH);
           
            if (f==JOptionPane.YES_NO_OPTION) {
                
                if (Funciones.isDeleteLocal(s)) {
                    JOptionPane.showMessageDialog(null, "Se Elimino el Local");
                    Funciones.setListarLocal("");
                    clean();
                    
                    
                }else{
                    JOptionPane.showMessageDialog(null, "No se Pudo Eliminar el Campo");
                }
                
            } else {
                JOptionPane.showMessageDialog(null, "Cancelado Exitoso");
            }
        }      
    }//GEN-LAST:event_btnBorarrActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        clean();
        btnGuardar.setVisible(true);
        btnActualizar.setVisible(false);
        lblId.setText(Funciones.extraerIdMaxLocal());
    }//GEN-LAST:event_jButton1ActionPerformed

    private void txtTelefonoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTelefonoActionPerformed
        
    }//GEN-LAST:event_txtTelefonoActionPerformed

    private void txtNombreKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNombreKeyTyped
       txtNombre.setText(txtNombre.getText().replaceAll("( )+", " "));
        if (txtNombre.getText().length()==0 && evt.getKeyChar()==KeyEvent.VK_SPACE) {
            evt.consume();
        }
           int tam = txtNombre.getText().length();
        if(tam>=30){
            evt.consume();
        } 
    }//GEN-LAST:event_txtNombreKeyTyped

    private void txtDireccionKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDireccionKeyTyped
        txtDireccion.setText(txtDireccion.getText().replaceAll("( )+", " "));
        Validaciones.Space(txtDireccion.getText().length(), evt);
           
        int tam = txtDireccion.getText().length();  
        if(tam>=300){
            evt.consume();
     } 
    }//GEN-LAST:event_txtDireccionKeyTyped

    private void btnimprimirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnimprimirActionPerformed
       try {
            Reportes reporte = new Reportes();
            reporte.ReporteLocal();
            
        } catch (JRException ex) {
            Logger.getLogger(Reportes.class.getName()).log(Level.SEVERE, null, ex);
        } catch(SQLException ex){
            Logger.getLogger(Reportes.class.getName()).log(Level.SEVERE, null, ex);
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_btnimprimirActionPerformed

    private void txtDireccionKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDireccionKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_TAB) {
                    if (evt.getModifiers() > 0) {
                        txtDireccion.transferFocusBackward();
                    } else {
                        txtDireccion.transferFocus();
                    }
                    evt.consume();
                }
    }//GEN-LAST:event_txtDireccionKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LOCAL_REGISTRO.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LOCAL_REGISTRO.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LOCAL_REGISTRO.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LOCAL_REGISTRO.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LOCAL_REGISTRO().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActualizar;
    public static javax.swing.JButton btnBorarr;
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnimprimir;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblId;
    public static javax.swing.JTable tblLocal;
    private javax.swing.JTextArea txtDireccion;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JFormattedTextField txtRTN;
    private javax.swing.JFormattedTextField txtTelefono;
    private javax.swing.JFormattedTextField txtTelefono2;
    // End of variables declaration//GEN-END:variables
}
