/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyectomp;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

import static proyectomp.USUARIOS.tablaUsu;

/**
 *
 * @author angel
 */
public class LOGIN extends javax.swing.JFrame {

    /**
     * Creates new form LOGIN
     */
    
    private String NombreUsu, Tipo_Usu, boni, cargos, cliente, compras, deduc, egres, 
            empleado, horario, ingres, invent, local, planilla, produc, provee,
            sar, ventas, usuarios;
    private String contra;
    public LOGIN() {
        initComponents();
        
       this.setLocationRelativeTo(null);
        
            
        }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtUsuar = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        txtPasw = new javax.swing.JPasswordField();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("USUARIO");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 89, -1, -1));

        jLabel2.setText("CONTRASEÑA");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 127, -1, -1));
        jPanel1.add(txtUsuar, new org.netbeans.lib.awtextra.AbsoluteConstraints(96, 86, 214, -1));

        jButton1.setText("ENTRAR");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 160, -1, -1));

        jButton2.setText("SALIR");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 160, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText("INGRESAR AL SISTEMA");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 30, -1, -1));

        txtPasw.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPaswActionPerformed(evt);
            }
        });
        jPanel1.add(txtPasw, new org.netbeans.lib.awtextra.AbsoluteConstraints(96, 124, 214, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/fondo 1.jpg"))); // NOI18N
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 350, 210));

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
public String Valor;
    
    
    void acceder(String usuario, String pass){
         try {
            
             try {
                  Connection con=DriverManager.getConnection("jdbc:sqlserver://192.168.0.11:1433;databaseName=PROYECTO_MP", "Irvingx", "Iopteamop12");
                   Statement sent = con.createStatement();
             ResultSet rs = sent.executeQuery("Select * from USUARIOS where Nombre_Usu = '"+usuario 
                    +"' AND Contrasenia_Usu = '"+pass+"' ");
             while(rs.next()){
           NombreUsu = rs.getString("Nombre_Usu");
           Tipo_Usu = rs.getString("TipoUsuario");
            boni = rs.getString("Boni_Usu");
            cargos = rs.getString("Cargos_Usu");
            cliente = rs.getString("Cliente_Usu");
            compras = rs.getString("Compras_Usu");
            deduc = rs.getString("Deducc_Usu");
            egres = rs.getString("Egres_Usu");
            empleado = rs.getString("Empleado_Usu");
            horario = rs.getString("Horario_Usu");
            ingres = rs.getString("Ingres_Usu");
            invent = rs.getString("Invent_Usu");
            local = rs.getString("Local_Usu");
            planilla = rs.getString("Planilla_Usu");
            produc = rs.getString("Producto_Usu");
            provee = rs.getString("Sar_Usu");
            sar = rs.getString("Sar_Usu");
            ventas = rs.getString("Ventas_Usu");
            usuarios = rs.getString("Usuarios_Usu");
             }
           if(txtUsuar.getText().equals("Admin")&& pass.equals("cusadmin")){
               JOptionPane.showMessageDialog(this, "Bienvenido Super Usuario");
               VENTANA_PRINCIPAL V = new VENTANA_PRINCIPAL();               
               V.setVisible(true);
      
        dispose();
            }else{
            if(txtUsuar.getText().equals(NombreUsu)){
               JOptionPane.showMessageDialog(this, "Bienvenido "+" "+NombreUsu);
               VENTANA_PRINCIPAL V = new VENTANA_PRINCIPAL();
               if(Tipo_Usu.equals("Cliente")){
                   V.setVerificar(1);
                 }
                     
                 if(cargos.equals("0")){
                     V.btnCargos.setVisible(false);
                 }
                 if(cliente.equals("0")){
                     V.btnCliente.setVisible(false);
                 }
                 if(compras.equals("0")){
                     V.btnCompras.setVisible(false);
                 }
//                 if(deduc.equals("0")){
//                     V.btnDeduc.setVisible(false);
//                 }
                 if(egres.equals("0")){
                     V.btnEgresos.setVisible(false);
                 }
                 if(empleado.equals("0")){
                     V.btnEmpleado.setVisible(false);
                 }
//                 if(horario.equals("0")){
//                     V.btnHorarios.setVisible(false);
//                 }
                 if(ingres.equals("0")){
                     V.btnIngreso.setVisible(false);
                 }
                 if(invent.equals("0")){
                     V.btnInventario.setVisible(false);
                 }
                 if(local.equals("0")){
                     V.btnLocal.setVisible(false);
                 }
                 if(planilla.equals("0")){
                     V.btnPlanill.setVisible(false);
                 }
                 if(produc.equals("0")){
                     V.btnProducto.setVisible(false);
                 }
                 if(provee.equals("0")){
                     V.btnProveedor.setVisible(false);
                 }
                 if(sar.equals("0")){
                     V.btnSar.setVisible(false);
                 }
                 if(ventas.equals("0")){
                     V.btnVentas.setVisible(false);
                     V.btnBoni.setVisible(false);
                 }     
                 if(usuarios.equals("0")){
                     V.btnUsuario.setVisible(false);
                     
                 }
                    V.setVisible(true);
              
        dispose();
                 }else{
                JOptionPane.showMessageDialog(this, "Usuario o Contraseña Invalida");
            }
        }
             } catch (Exception e) {
                   Connection con=DriverManager.getConnection("jdbc:sqlserver://localhost;databaseName=PROYECTO_MP", "sa", "123");
                    Statement sent = con.createStatement();
             ResultSet rs = sent.executeQuery("Select * from USUARIOS where Nombre_Usu = '"+usuario 
                    +"' AND Contrasenia_Usu = '"+pass+"' ");
             while(rs.next()){
           NombreUsu = rs.getString("Nombre_Usu");
           Tipo_Usu = rs.getString("TipoUsuario");
            boni = rs.getString("Boni_Usu");
            cargos = rs.getString("Cargos_Usu");
            cliente = rs.getString("Cliente_Usu");
            compras = rs.getString("Compras_Usu");
            deduc = rs.getString("Deducc_Usu");
            egres = rs.getString("Egres_Usu");
            empleado = rs.getString("Empleado_Usu");
            horario = rs.getString("Horario_Usu");
            ingres = rs.getString("Ingres_Usu");
            invent = rs.getString("Invent_Usu");
            local = rs.getString("Local_Usu");
            planilla = rs.getString("Planilla_Usu");
            produc = rs.getString("Producto_Usu");
            provee = rs.getString("Sar_Usu");
            sar = rs.getString("Sar_Usu");
            ventas = rs.getString("Ventas_Usu");
            usuarios = rs.getString("Usuarios_Usu");
             }
           if(txtUsuar.getText().equals("Admin")&& pass.equals("cusadmin")){
               JOptionPane.showMessageDialog(this, "Bienvenido Super Usuario");
               VENTANA_PRINCIPAL V = new VENTANA_PRINCIPAL();               
               V.setVisible(true);
      
        dispose();
            }else{
            if(txtUsuar.getText().equals(NombreUsu)){
               JOptionPane.showMessageDialog(this, "Bienvenido "+" "+NombreUsu);
               VENTANA_PRINCIPAL V = new VENTANA_PRINCIPAL();
               if(Tipo_Usu.equals("Cliente")){
                   V.setVerificar(1);
                 }
                     
                 if(cargos.equals("0")){
                     V.btnCargos.setVisible(false);
                 }
                 if(cliente.equals("0")){
                     V.btnCliente.setVisible(false);
                 }
                 if(compras.equals("0")){
                     V.btnCompras.setVisible(false);
                 }
//                 if(deduc.equals("0")){
//                     V.btnDeduc.setVisible(false);
//                 }
                 if(egres.equals("0")){
                     V.btnEgresos.setVisible(false);
                 }
                 if(empleado.equals("0")){
                     V.btnEmpleado.setVisible(false);
                 }
//                 if(horario.equals("0")){
//                     V.btnHorarios.setVisible(false);
//                 }
                 if(ingres.equals("0")){
                     V.btnIngreso.setVisible(false);
                 }
                 if(invent.equals("0")){
                     V.btnInventario.setVisible(false);
                 }
                 if(local.equals("0")){
                     V.btnLocal.setVisible(false);
                 }
                 if(planilla.equals("0")){
                     V.btnPlanill.setVisible(false);
                 }
                 if(produc.equals("0")){
                     V.btnProducto.setVisible(false);
                 }
                 if(provee.equals("0")){
                     V.btnProveedor.setVisible(false);
                 }
                 if(sar.equals("0")){
                     V.btnSar.setVisible(false);
                 }
                 if(ventas.equals("0")){
                     V.btnVentas.setVisible(false);
                     V.btnBoni.setVisible(false);
                 }     
                 if(usuarios.equals("0")){
                     V.btnUsuario.setVisible(false);
                     
                 }
                    V.setVisible(true);
              
        dispose();
                 }else{
                JOptionPane.showMessageDialog(this, "Usuario o Contraseña Invalida");
            }
        }
             }
             //Connection con=DriverManager.getConnection("jdbc:sqlserver://192.168.0.14:1433;databaseName=PROYECTO_MP", "Irvingx", "Iopteamop12");
            
       
             
        } catch (Exception ex) {
            Logger.getLogger(Funciones.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(null, "No se pudo establecer la conexion con el servidor");
            
        }
        
        this.setLocationRelativeTo(null);
       
            
        
    }
        
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String usu = txtUsuar.getText();    
        String pass =new String(txtPasw.getPassword());
        
        acceder(usu, pass);    
    }//GEN-LAST:event_jButton1ActionPerformed

    private void txtPaswActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPaswActionPerformed
        jButton1ActionPerformed(evt);
    }//GEN-LAST:event_txtPaswActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LOGIN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LOGIN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LOGIN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LOGIN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LOGIN().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    public static javax.swing.JPasswordField txtPasw;
    public static javax.swing.JTextField txtUsuar;
    // End of variables declaration//GEN-END:variables
}
