/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyectomp;

import javax.swing.JOptionPane;
import static proyectomp.DETALLE_PLANILLAS.lblIdD;

/**
 *
 * @author Calix
 */
public class MostarEmpleadosPlanilla extends javax.swing.JFrame {

    /**
     * Creates new form MostarEmpleadosPlanilla
     */
    public MostarEmpleadosPlanilla() {
        initComponents();
        Funciones.setListarEmp("");
        tblEMP.setSelectionMode(NORMAL);
        tblEMP.getTableHeader().setReorderingAllowed(false);
        
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblEMP = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        tblEMP.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Id", "Nombres", "Apellidos", "Identidad", "Cargo", "Sueldo"
            }
        ));
        jScrollPane1.setViewportView(tblEMP);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Selecciones un empleado");

        jButton1.setText("SELECCIONAR");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(124, 124, 124))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(181, 181, 181)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(30, 30, 30)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(31, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        int fila = tblEMP.getSelectedRow();
        Funciones.setListarDetalle(lblIdD.getText());  
        String id;
        
       // DETALLE_PLANILLAS D = new DETALLE_PLANILLAS();
        
       
//        String Id_E = tblEMP.getValueAt(fila, 1).toString();
//        jLabel1.setText(Id_E);
//        Funciones.repetido(this.jLabel1.getText());
//        
//        String id_a = String.valueOf(jLabel1.getText());
//        
//        
//        for(int i=0; i< DETALLE_PLANILLAS.tblMostrarEmp.getRowCount(); i++){
//            if(DETALLE_PLANILLAS.tblMostrarEmp.getValueAt(i,1).equals(jLabel1.getText())){
//              JOptionPane.showMessageDialog(null, "Ya esta registrado");
//            }
//        }
        int a =0;
        for(int i=0; i< DETALLE_PLANILLAS.tblMostrarEmp.getRowCount(); i++){
            if(DETALLE_PLANILLAS.tblMostrarEmp.getValueAt(i,0).toString().equals(tblEMP.getValueAt(fila, 0).toString())){
                a+=1;
              //JOptionPane.showMessageDialog(null, "Ya esta registrado");
            }
        }
        if(a>0){
            JOptionPane.showMessageDialog(null, "Ya existe");
        }else{
        
        
        
        
//        id = tblEMP.getValueAt(fila, 0).toString();
        
        DETALLE_PLANILLAS.lblId.setText(tblEMP.getValueAt(fila, 0).toString());
        DETALLE_PLANILLAS.lblNombre.setText(tblEMP.getValueAt(fila, 1).toString());
        DETALLE_PLANILLAS.lblApellido.setText(tblEMP.getValueAt(fila, 2).toString());
        DETALLE_PLANILLAS.lblCa.setText(tblEMP.getValueAt(fila, 4).toString());
        DETALLE_PLANILLAS.lblSue.setText(tblEMP.getValueAt(fila, 5).toString());
        
    
        
//                C.lblId.setText(this.lblId.getText());
//        C.lblNombre.setText(this.lblName.getText());
//        C.lblApellido.setText(this.LblApe.getText());
//        C.lblIdD.setText(this.lblIdP.getText());
//        C.lblSue.setText(this.lblSue.getText());
//        C.lblCa.setText(this.lblCa.getText());
//        C.pagoooo.setText(this.pagooo.getText());
        
//        Planilla c = c.lblId.setText(tblEMP.getValueAt(fila, 0).toString());
        
 //       Planilla c = new Planilla();
//         c.lblId.setText(tblEMP.getValueAt(fila, 0).toString());
//         c.lblName.setText(tblEMP.getValueAt(fila, 1).toString());
//         c.lblApe.setText(tblEMP.getValueAt(fila, 2).toString());
        
         
//        c.setVisible(true);
       // D.setVisible(true);
        Funciones.sumarColumn();
          Funciones.sumarTotalAPagar();
        dispose();
        }
        
        
        
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MostarEmpleadosPlanilla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MostarEmpleadosPlanilla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MostarEmpleadosPlanilla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MostarEmpleadosPlanilla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MostarEmpleadosPlanilla().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    public static javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    public static javax.swing.JTable tblEMP;
    // End of variables declaration//GEN-END:variables
}
