/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyectomp;

import javax.swing.JOptionPane;
import javax.swing.JTextField;
import static proyectomp.COMPRA_MATERIA_PRIMA.tblDetalleCompra;
import static proyectomp.MostrarPlanillas.tbl;

/**
 *
 * @author espin
 */
public class Mostrar_Compras extends javax.swing.JFrame {

    /**
     * Creates new form Mostrar_Compras
     */
    public Mostrar_Compras() {
        initComponents();
        Funciones_Henry.setListarCompras("");
         this.setLocationRelativeTo(null);
         setDefaultCloseOperation(DISPOSE_ON_CLOSE);
         tblCompras.setSelectionMode(NORMAL);
         tblCompras.getTableHeader().setReorderingAllowed(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblCompras = new javax.swing.JTable();
        btnRegistrar = new javax.swing.JButton();
        btnEditar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(255, 102, 0));

        jPanel1.setBackground(new java.awt.Color(255, 102, 0));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setText("COMPRAS");

        tblCompras.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Fecha de la Compra", "Fecha de Registro", "Numero de Factura", "Proveedor", "Id Proveedor", "Telefono Proveedor", "EMail Proveedor", "RTN Proveedor"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblCompras);
        if (tblCompras.getColumnModel().getColumnCount() > 0) {
            tblCompras.getColumnModel().getColumn(5).setMinWidth(0);
            tblCompras.getColumnModel().getColumn(5).setPreferredWidth(0);
            tblCompras.getColumnModel().getColumn(5).setMaxWidth(0);
            tblCompras.getColumnModel().getColumn(6).setMinWidth(0);
            tblCompras.getColumnModel().getColumn(6).setPreferredWidth(0);
            tblCompras.getColumnModel().getColumn(6).setMaxWidth(0);
            tblCompras.getColumnModel().getColumn(7).setMinWidth(0);
            tblCompras.getColumnModel().getColumn(7).setPreferredWidth(0);
            tblCompras.getColumnModel().getColumn(7).setMaxWidth(0);
            tblCompras.getColumnModel().getColumn(8).setMinWidth(0);
            tblCompras.getColumnModel().getColumn(8).setPreferredWidth(0);
            tblCompras.getColumnModel().getColumn(8).setMaxWidth(0);
        }

        btnRegistrar.setText("Registrar");
        btnRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarActionPerformed(evt);
            }
        });

        btnEditar.setText("Editar");
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(33, 33, 33)
                                .addComponent(btnRegistrar, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(292, 292, 292)
                                .addComponent(btnEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(248, 248, 248)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 454, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRegistrar, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(278, 278, 278)
                .addComponent(jLabel2)
                .addContainerGap(383, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 550, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
        int filaa= tblCompras.getSelectedRow();
        COMPRA_MATERIA_PRIMA_UPDATE S = new COMPRA_MATERIA_PRIMA_UPDATE();
        COMPRA_MATERIA_PRIMA_UPDATE.lblId.setText(tblCompras.getValueAt(filaa, 0).toString());
        COMPRA_MATERIA_PRIMA_UPDATE.lblID.setText(tblCompras.getValueAt(filaa, 4).toString());
        COMPRA_MATERIA_PRIMA_UPDATE.txtNumeroFactura.setText(tblCompras.getValueAt(filaa, 3).toString());
        COMPRA_MATERIA_PRIMA_UPDATE.lblId.setText(tblCompras.getValueAt(filaa, 0).toString());
        COMPRA_MATERIA_PRIMA_UPDATE.lblId.setText(tblCompras.getValueAt(filaa, 0).toString());
        COMPRA_MATERIA_PRIMA_UPDATE.lblID.setText(tblCompras.getValueAt(filaa, 5).toString());
        COMPRA_MATERIA_PRIMA_UPDATE.lblNombre.setText(tblCompras.getValueAt(filaa, 4).toString());
        COMPRA_MATERIA_PRIMA_UPDATE.lblTelefono.setText(tblCompras.getValueAt(filaa, 6).toString());
        ((JTextField)COMPRA_MATERIA_PRIMA_UPDATE.txtFechaCompra.getDateEditor()).setText(tblCompras.getValueAt(filaa, 1).toString());
        COMPRA_MATERIA_PRIMA_UPDATE.lblEmail.setText(tblCompras.getValueAt(filaa, 7).toString());
        COMPRA_MATERIA_PRIMA_UPDATE.lblRTN.setText(tblCompras.getValueAt(filaa, 8).toString());
        
        COMPRA_MATERIA_PRIMA_UPDATE.lblFechaRegistro.setText(tblCompras.getValueAt(filaa, 2).toString());
        Funciones_Henry.setListarDetalleCompra(tblCompras.getValueAt(filaa, 0).toString());
        double acum = 0;
        for (int i = 0; i < COMPRA_MATERIA_PRIMA_UPDATE.tblDetalleCompra.getRowCount(); i++) {
            double var = Double.parseDouble(COMPRA_MATERIA_PRIMA_UPDATE.tblDetalleCompra.getValueAt(i, 5).toString());
            acum = acum+var;
            
        }
        COMPRA_MATERIA_PRIMA_UPDATE.lblTotal.setText(String.valueOf(acum));
        S.setVisible(true);
        
        
    }//GEN-LAST:event_btnEditarActionPerformed

    private void btnRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarActionPerformed
         COMPRA_MATERIA_PRIMA c = new COMPRA_MATERIA_PRIMA();
         c.setVisible(true);
// TODO add your handling code here:
    }//GEN-LAST:event_btnRegistrarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Mostrar_Compras.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Mostrar_Compras.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Mostrar_Compras.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Mostrar_Compras.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Mostrar_Compras().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnRegistrar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    public static javax.swing.JTable tblCompras;
    // End of variables declaration//GEN-END:variables
}
