/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyectomp;

import java.awt.Event;
import java.awt.event.KeyEvent;
import java.sql.Date;
import java.text.SimpleDateFormat;
import javax.swing.InputMap;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.KeyStroke;
import static proyectomp.Planilla_Update_2.lblSistema;
import static proyectomp.Planilla_Update_2.observaciones;

/**
 *
 * @author Calix
 */
public class Planilla extends javax.swing.JFrame {

    /**
     * Creates new form Planilla
     */
    public Planilla() {
        initComponents();
        Funciones.extraerIdMaxPlanilla();
        ((JTextField)this.Fecha_Pago.getDateEditor()).setEditable(false);
        InputMap map3 = observaciones.getInputMap(JTextField.WHEN_FOCUSED); 
    map3.put(KeyStroke.getKeyStroke(KeyEvent.VK_V, Event.CTRL_MASK), "null");
        
        lblIdP.setText(Funciones.extraerIdMaxPlanilla());
         java.util.Date fecha = new java.util.Date();
               SimpleDateFormat formato = new SimpleDateFormat("yyy-MM-dd");
               lblFechaSistema.setText(formato.format(fecha));
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        validacion = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lblIdP = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        cmbTipo = new javax.swing.JComboBox<String>();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        btnGuardar = new javax.swing.JButton();
        lblName = new javax.swing.JLabel();
        lblId = new javax.swing.JLabel();
        LblApe = new javax.swing.JLabel();
        Fecha_Pago = new com.toedter.calendar.JDateChooser();
        lblCa = new javax.swing.JLabel();
        lblSue = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtObs = new javax.swing.JTextArea();
        lblFechaSistema = new javax.swing.JLabel();
        cmbPeriodo = new javax.swing.JComboBox<String>();
        jLabel9 = new javax.swing.JLabel();
        pagooo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        validacion.setBackground(new java.awt.Color(255, 0, 0));
        validacion.setForeground(new java.awt.Color(255, 51, 51));
        jPanel1.add(validacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 450, 280, 30));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setText("PLANILLA");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(631, 11, 149, -1));

        jLabel2.setText("Id");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(473, 82, 174, -1));

        lblIdP.setText("1");
        jPanel1.add(lblIdP, new org.netbeans.lib.awtextra.AbsoluteConstraints(803, 82, 196, -1));

        jLabel4.setText("Tipo");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(473, 219, -1, -1));

        cmbTipo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Ordinaria", "Extraordinaria" }));
        jPanel1.add(cmbTipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(803, 216, 165, -1));

        jLabel5.setText("Periodo");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(473, 117, 174, -1));

        jLabel6.setText("Fecha Creacion");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(473, 152, -1, -1));

        jLabel7.setText("Fecha Pago");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(473, 184, -1, -1));

        btnGuardar.setText("GUARDAR");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });
        jPanel1.add(btnGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 550, 144, 61));
        jPanel1.add(lblName, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 420, 94, 14));
        jPanel1.add(lblId, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 400, 43, 14));
        jPanel1.add(LblApe, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 400, 63, 14));

        Fecha_Pago.setDateFormatString("yyy-MM-dd");
        Fecha_Pago.setMaxSelectableDate(new java.util.Date(253370790074000L));
        Fecha_Pago.setMinSelectableDate(new java.util.Date());
        jPanel1.add(Fecha_Pago, new org.netbeans.lib.awtextra.AbsoluteConstraints(803, 183, 218, -1));
        jPanel1.add(lblCa, new org.netbeans.lib.awtextra.AbsoluteConstraints(1040, 410, 73, 14));
        jPanel1.add(lblSue, new org.netbeans.lib.awtextra.AbsoluteConstraints(1090, 410, 92, 14));

        jLabel3.setText("Observaciones");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 250, -1, -1));

        txtObs.setColumns(20);
        txtObs.setRows(5);
        txtObs.setMaximumSize(new java.awt.Dimension(10, 10));
        txtObs.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtObsKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtObsKeyTyped(evt);
            }
        });
        jScrollPane1.setViewportView(txtObs);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 260, 217, -1));

        lblFechaSistema.setText("fecha");
        jPanel1.add(lblFechaSistema, new org.netbeans.lib.awtextra.AbsoluteConstraints(803, 158, 218, -1));

        cmbPeriodo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Semanal", "Quincenal", "Mensual" }));
        jPanel1.add(cmbPeriodo, new org.netbeans.lib.awtextra.AbsoluteConstraints(803, 114, 196, -1));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/fondo2.jpg"))); // NOI18N
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1390, 810));

        pagooo.setText("jLabel10");
        jPanel1.add(pagooo, new org.netbeans.lib.awtextra.AbsoluteConstraints(175, 233, -1, -1));

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        if(txtObs.getText().length()==0 || 
                //this.sexo.getSelectedItem().equals(0)||
                ((JTextField)this.Fecha_Pago.getDateEditor().getUiComponent()).getText().length()==0){
            this.validacion.setText("TODOS LOS CAMPOS SON NECESARIOS");
        }else{
        String selct =((JTextField)this.Fecha_Pago.getDateEditor().getUiComponent()).getText();
       pagooo.setText(selct);
        Sentencias s = new Sentencias();
       s.setPeriodo_Pla(this.cmbTipo.getSelectedItem().toString());
       s.setObservaciones_Pla(this.txtObs.getText());
       s.setFecha_Creacion_Pla(this.lblFechaSistema.getText());
       //s.setFecha_Creacion_Pla(((JTextField)this.Fecha_Creacion.getDateEditor().getUiComponent()).getText());
       s.setFecha_Pago_Pla(((JTextField)this.Fecha_Pago.getDateEditor().getUiComponent()).getText());
      // s.setPeriodo_Pla(((JTextField)this.Fecha_Pago.getDateEditor().getUiComponent()).getText());
       s.setTipo_Pla(this.cmbTipo.getSelectedItem().toString());
//       s.setId_Emp(Integer.parseInt(this.lblId.getText()));
       
        if (Funciones.isRegisterPlanilla(s)) {
          JOptionPane.showMessageDialog(this, "Nueva planilla creada");
            
            
            }else{
                JOptionPane.showMessageDialog(this, "Fallo");
                
            }
            
            
        
        
        DETALLE_PLANILLAS C = new DETALLE_PLANILLAS();
//        C.lblId.setText(this.lblId.getText());
//        C.lblNombre.setText(this.lblName.getText());
//        C.lblApellido.setText(this.LblApe.getText());
        //C.lblIdD.setText(this.lblIdP.getText());
//        C.lblSue.setText(this.lblSue.getText());
//        C.lblCa.setText(this.lblCa.getText());
        C.pagoooo.setText(this.pagooo.getText());
        
       C.setVisible(true); 
        
        dispose();}
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void txtObsKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtObsKeyTyped
       int tam = txtObs.getText().length();
        if(tam>=250){
            evt.consume();
        } // TODO add your handling code here:
    }//GEN-LAST:event_txtObsKeyTyped

    private void txtObsKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtObsKeyPressed
 txtObs.setText(txtObs.getText().replaceAll("( )+", " "));
        if (txtObs.getText().length()==0 && evt.getKeyChar()==KeyEvent.VK_SPACE) {
            evt.consume();
            
        }
        if (evt.getKeyCode() == KeyEvent.VK_TAB) {
                    if (evt.getModifiers() > 0) {
                        txtObs.transferFocusBackward();
                    } else {
                        txtObs.transferFocus();
                    }
                    evt.consume();
                }         // TODO add your handling code here:
    }//GEN-LAST:event_txtObsKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Planilla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Planilla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Planilla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Planilla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Planilla().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.toedter.calendar.JDateChooser Fecha_Pago;
    public static javax.swing.JLabel LblApe;
    private javax.swing.JButton btnGuardar;
    public static javax.swing.JComboBox<String> cmbPeriodo;
    private javax.swing.JComboBox<String> cmbTipo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    public static javax.swing.JLabel lblCa;
    public static javax.swing.JLabel lblFechaSistema;
    public static javax.swing.JLabel lblId;
    private javax.swing.JLabel lblIdP;
    public static javax.swing.JLabel lblName;
    public static javax.swing.JLabel lblSue;
    public static javax.swing.JLabel pagooo;
    private javax.swing.JTextArea txtObs;
    private javax.swing.JLabel validacion;
    // End of variables declaration//GEN-END:variables
}
