/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyectomp;

import java.awt.Event;
import java.awt.event.KeyEvent;
import java.sql.Date;
import java.text.SimpleDateFormat;
import javax.swing.InputMap;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.KeyStroke;
import static proyectomp.DETALLE_PLANILLAS.lblIdD;

/**
 *
 * @author Calix
 */
public class Planilla_Update_2 extends javax.swing.JFrame {

    /**
     * Creates new form Planilla
     */
    public Planilla_Update_2() {
        initComponents();
        ((JTextField)this.Fecha_Pago.getDateEditor()).setEditable(false);
        
        InputMap map3 = observaciones.getInputMap(JTextField.WHEN_FOCUSED); 
    map3.put(KeyStroke.getKeyStroke(KeyEvent.VK_V, Event.CTRL_MASK), "null");
        
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        VER = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lblIdP = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        cmbTipo = new javax.swing.JComboBox<String>();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        btnGuardar = new javax.swing.JButton();
        lblName = new javax.swing.JLabel();
        lblId = new javax.swing.JLabel();
        LblApe = new javax.swing.JLabel();
        Fecha_Pago = new com.toedter.calendar.JDateChooser();
        lblCa = new javax.swing.JLabel();
        lblSue = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        observaciones = new javax.swing.JTextArea();
        lblSistema = new javax.swing.JLabel();
        cmbPeriodo = new javax.swing.JComboBox<String>();
        jLabel9 = new javax.swing.JLabel();
        pagooooo = new javax.swing.JLabel();
        fechaas = new javax.swing.JTextField();
        idDetalle = new javax.swing.JLabel();
        total = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        VER.setText("Ver Detalle");
        VER.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VERActionPerformed(evt);
            }
        });
        jPanel1.add(VER, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 450, 130, 60));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setText("PLANILLA");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(631, 11, 149, -1));

        jLabel2.setText("Id");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(473, 82, 174, -1));

        lblIdP.setText("1");
        jPanel1.add(lblIdP, new org.netbeans.lib.awtextra.AbsoluteConstraints(912, 82, 196, -1));

        jLabel4.setText("Tipo");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(473, 219, -1, -1));

        cmbTipo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Ordinaria", "Extraordinaria" }));
        jPanel1.add(cmbTipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(803, 216, 165, -1));

        jLabel5.setText("Periodo");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(473, 117, 174, -1));

        jLabel6.setText("Fecha Creacion");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(473, 152, -1, -1));

        jLabel7.setText("Fecha Pago");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(473, 184, -1, -1));

        btnGuardar.setText("EDITAR");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });
        jPanel1.add(btnGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 440, 144, 61));
        jPanel1.add(lblName, new org.netbeans.lib.awtextra.AbsoluteConstraints(553, 322, 94, 14));
        jPanel1.add(lblId, new org.netbeans.lib.awtextra.AbsoluteConstraints(473, 322, 43, 14));
        jPanel1.add(LblApe, new org.netbeans.lib.awtextra.AbsoluteConstraints(676, 322, 63, 14));

        Fecha_Pago.setDateFormatString("yyy-MM-dd");
        Fecha_Pago.setMaxSelectableDate(new java.util.Date(253370790079000L));
        Fecha_Pago.setMinSelectableDate(new java.util.Date());
        jPanel1.add(Fecha_Pago, new org.netbeans.lib.awtextra.AbsoluteConstraints(803, 183, 218, -1));
        jPanel1.add(lblCa, new org.netbeans.lib.awtextra.AbsoluteConstraints(1024, 322, 73, 14));
        jPanel1.add(lblSue, new org.netbeans.lib.awtextra.AbsoluteConstraints(1130, 322, 92, 14));

        jLabel3.setText("Observaciones");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 260, -1, -1));

        observaciones.setColumns(20);
        observaciones.setRows(5);
        observaciones.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                observacionesKeyTyped(evt);
            }
        });
        jScrollPane1.setViewportView(observaciones);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 260, 217, -1));

        lblSistema.setText("fecha");
        jPanel1.add(lblSistema, new org.netbeans.lib.awtextra.AbsoluteConstraints(803, 158, 218, -1));

        cmbPeriodo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Semanal", "Quincenal", "Mensual" }));
        jPanel1.add(cmbPeriodo, new org.netbeans.lib.awtextra.AbsoluteConstraints(803, 114, 218, -1));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/fondo2.jpg"))); // NOI18N
        jLabel9.setToolTipText("");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1400, 810));

        pagooooo.setText("jLabel10");
        jPanel1.add(pagooooo, new org.netbeans.lib.awtextra.AbsoluteConstraints(56, 445, -1, -1));

        fechaas.setText("jTextField1");
        jPanel1.add(fechaas, new org.netbeans.lib.awtextra.AbsoluteConstraints(139, 512, -1, -1));

        idDetalle.setText("jLabel10");
        jPanel1.add(idDetalle, new org.netbeans.lib.awtextra.AbsoluteConstraints(228, 515, -1, -1));

        total.setText("jLabel11");
        jPanel1.add(total, new org.netbeans.lib.awtextra.AbsoluteConstraints(313, 515, -1, -1));

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
       Sentencias s = new Sentencias();
        if(observaciones.getText().length()==0 || 
                //this.sexo.getSelectedItem().equals(0)||
                ((JTextField)this.Fecha_Pago.getDateEditor().getUiComponent()).getText().length()==0){
            JOptionPane.showMessageDialog(null, "Todos los campos son requeridos");
        }else{
       String selct =((JTextField)this.Fecha_Pago.getDateEditor().getUiComponent()).getText();
       pagooooo.setText(selct);
       s.setId_Pla(Integer.parseInt(this.lblIdP.getText()));
       s.setObservaciones_Pla(this.observaciones.getText());
       s.setFecha_Creacion_Pla(this.lblSistema.getText());
       //s.setFecha_Creacion_Pla(((JTextField)this.Fecha_Creacion.getDateEditor().getUiComponent()).getText());
       s.setFecha_Pago_Pla(((JTextField)this.Fecha_Pago.getDateEditor().getUiComponent()).getText());
       s.setPeriodo_Pla(this.cmbPeriodo.getSelectedItem().toString());
//       s.setPeriodo_Pla(((JTextField)this.periodo.getDateEditor().getUiComponent()).getText());
       s.setTipo_Pla(this.cmbTipo.getSelectedItem().toString());
//       s.setId_Emp(Integer.parseInt(this.lblId.getText()));
       
        if (Funciones.isUpdatePlanilla(s)) {
          JOptionPane.showMessageDialog(this, "Datos de la planilla Actualizados");
         
        
            
            
            }else{
                JOptionPane.showMessageDialog(this, "Fallo");
                
            }
            
            
        
        
        
        DETALLE_PLANILLAS_UPDATE C = new DETALLE_PLANILLAS_UPDATE();
        
        
//        C.lblId.setText(this.lblId.getText());
//        C.lblNombre.setText(this.lblName.getText());
//        C.lblApellido.setText(this.LblApe.getText());
        C.lblIdD.setText(this.lblIdP.getText());
//        C.lblxxx.setText(this.idDetalle.getText());
//        C.lblSue.setText(this.lblSue.getText());
//        C.lblCa.setText(this.lblCa.getText());
//        C.lblPago.setText(this.total.getText());
        C.pagoooo.setText(this.pagooooo.getText());
         Funciones.setListarDetalleUpdate(lblIdP.getText());
         Funciones.sumarPLANILLAUPDATE();
        
        C.setVisible(true);
//         Funciones.setListarJoinBoniUpdate(lblId.getText(), lblSistema.getText(), pagooooo.getText(), lblIdP.getText());
//          Funciones.setListarJoinDeduUpdate(lblId.getText(), lblSistema.getText(), pagooooo.getText(), lblIdP.getText());
//          Funciones.sumarColumnUpdate();
//          Funciones.sumarColumnBoniUpdate();
          
          dispose();
        }
        
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void VERActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VERActionPerformed
       DETALLE_PLANILLAS_UPDATE C = new DETALLE_PLANILLAS_UPDATE();
        
        
//        C.lblId.setText(this.lblId.getText());
//        C.lblNombre.setText(this.lblName.getText());
//        C.lblApellido.setText(this.LblApe.getText());
        C.lblIdD.setText(this.lblIdP.getText());
        C.btnDedu.setEnabled(false);
        C.btnBoni.setEnabled(false);
        C.btnDelete.setEnabled(false);
        C.btnEmp.setEnabled(false);
//        C.lblSue.setText(this.lblSue.getText());
//        C.lblCa.setText(this.lblCa.getText());
//        C.lblPago.setText(this.total.getText());
        C.pagoooo.setText(this.pagooooo.getText());
         Funciones.setListarDetalleUpdate(lblIdP.getText());
         Funciones.sumarPLANILLAUPDATE();
        
        C.setVisible(true);
//         Funciones.setListarJoinBoniUpdate(lblId.getText(), lblSistema.getText(), pagooooo.getText(), lblIdP.getText());
//          Funciones.setListarJoinDeduUpdate(lblId.getText(), lblSistema.getText(), pagooooo.getText(), lblIdP.getText());
//          Funciones.sumarColumnUpdate();
//          Funciones.sumarColumnBoniUpdate();
          
          dispose();
    }//GEN-LAST:event_VERActionPerformed

    private void observacionesKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_observacionesKeyTyped
       
        int tam = observaciones.getText().length();
        if(tam>=250){
            evt.consume();
        }// TODO add your handling code here:
    }//GEN-LAST:event_observacionesKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Planilla_Update_2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Planilla_Update_2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Planilla_Update_2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Planilla_Update_2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Planilla_Update_2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static com.toedter.calendar.JDateChooser Fecha_Pago;
    public static javax.swing.JLabel LblApe;
    private javax.swing.JButton VER;
    public static javax.swing.JButton btnGuardar;
    public static javax.swing.JComboBox<String> cmbPeriodo;
    public static javax.swing.JComboBox<String> cmbTipo;
    public static javax.swing.JTextField fechaas;
    public static javax.swing.JLabel idDetalle;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    public static javax.swing.JLabel lblCa;
    public static javax.swing.JLabel lblId;
    public javax.swing.JLabel lblIdP;
    public static javax.swing.JLabel lblName;
    public static javax.swing.JLabel lblSistema;
    public static javax.swing.JLabel lblSue;
    public static javax.swing.JTextArea observaciones;
    public static javax.swing.JLabel pagooooo;
    public static javax.swing.JLabel total;
    // End of variables declaration//GEN-END:variables
}
