/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyectomp;

import java.awt.Event;
import java.awt.event.KeyEvent;
import javax.swing.InputMap;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.KeyStroke;
import static proyectomp.EMPLEADOS.tblTabla;

/**
 *
 * @author Calix
 */
public class SAR extends javax.swing.JFrame {

    /**
     * Creates new form Local
     */
    String dato;
    int dpart1, dpart2, dpart3, dpart4, dpart5, dpart6,dpart7, dpart8;
    public SAR() {
        initComponents();
        ((JTextField)calendarLim.getDateEditor()).setEditable(false);
        tblSAR.setSelectionMode(NORMAL);
        tblSAR.getTableHeader().setReorderingAllowed(false) ;
        btnActualizar.setVisible(false);
        esta.setVisible(true);
        this.setLocationRelativeTo(null);
        lblId.setText(Funciones_Angel.extraerIdMaxSar());
        Funciones_Angel.setListarSar("");
        InputMap map2 = jformaCai.getInputMap(JTextField.WHEN_FOCUSED); 
    map2.put(KeyStroke.getKeyStroke(KeyEvent.VK_V, Event.CTRL_MASK), "null");
    
    InputMap map3 = txtIpto.getInputMap(JTextField.WHEN_FOCUSED); 
    map3.put(KeyStroke.getKeyStroke(KeyEvent.VK_V, Event.CTRL_MASK), "null");
    
    
    }
    
    
    private void clean(){
        JforRangoDel.setText("");
        jForRAngoAl.setText("");
        jformaCai.setText("");
        calendarLim.setDate(null);
        txtIpto.setText("");
        JforRangoDel.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        res = new javax.swing.JLabel();
        txtIpto = new javax.swing.JTextField();
        calendarLim = new com.toedter.calendar.JDateChooser();
        jLabel8 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jformaCai = new javax.swing.JFormattedTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jForRAngoAl = new javax.swing.JFormattedTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        JforRangoDel = new javax.swing.JFormattedTextField();
        lblId = new javax.swing.JLabel();
        btnGuardar = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblSAR = new javax.swing.JTable();
        btnBorarr = new javax.swing.JButton();
        btnActualizar = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        esta = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        res.setText("%");
        jPanel1.add(res, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 240, -1, -1));

        txtIpto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtIptoKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtIptoKeyTyped(evt);
            }
        });
        jPanel1.add(txtIpto, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 240, 70, -1));

        calendarLim.setDateFormatString("yyyy-MM-dd");
        jPanel1.add(calendarLim, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 200, 250, -1));

        jLabel8.setText("Impuesto");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 240, -1, -1));

        jLabel6.setText("Fecha Limite:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 200, -1, -1));

        try {
            jformaCai.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("#A#A#A AA#AA ###AAA #A##AA ####A# ##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jformaCai.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jformaCaiMouseClicked(evt);
            }
        });
        jformaCai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jformaCaiActionPerformed(evt);
            }
        });
        jPanel1.add(jformaCai, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 160, 250, -1));

        jLabel5.setText("CAI");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 160, -1, -1));

        jLabel9.setText("Al:");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 120, -1, -1));

        jLabel4.setText("Rango Del:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 80, -1, -1));

        try {
            jForRAngoAl.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###-###-##-########")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jPanel1.add(jForRAngoAl, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 120, 250, -1));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setText("DATOS SAR");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 10, -1, -1));

        jLabel2.setText("Id");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(44, 49, 37, -1));

        try {
            JforRangoDel.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###-###-##-########")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jPanel1.add(JforRangoDel, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 80, 250, -1));

        lblId.setText("1");
        jPanel1.add(lblId, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 50, 62, 10));

        btnGuardar.setText("GUARDAR");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });
        jPanel1.add(btnGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 310, -1, -1));

        tblSAR.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null}
            },
            new String [] {
                "Id", "Rango De", "Al", "CAI", "Fecha Limite", "# Factura"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tblSAR);
        if (tblSAR.getColumnModel().getColumnCount() > 0) {
            tblSAR.getColumnModel().getColumn(0).setResizable(false);
            tblSAR.getColumnModel().getColumn(0).setPreferredWidth(1);
            tblSAR.getColumnModel().getColumn(1).setResizable(false);
            tblSAR.getColumnModel().getColumn(2).setResizable(false);
            tblSAR.getColumnModel().getColumn(3).setResizable(false);
            tblSAR.getColumnModel().getColumn(4).setResizable(false);
            tblSAR.getColumnModel().getColumn(5).setResizable(false);
        }

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 340, 950, 150));

        btnBorarr.setText("BORRAR");
        btnBorarr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBorarrActionPerformed(evt);
            }
        });
        jPanel1.add(btnBorarr, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 500, 111, 35));

        btnActualizar.setText("ACTUALIZAR");
        btnActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarActionPerformed(evt);
            }
        });
        jPanel1.add(btnActualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 310, -1, -1));

        jButton1.setText("LIMPIAR");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 310, -1, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/fondo2.jpg"))); // NOI18N
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, 550));

        esta.setText("jTextField1");
        jPanel1.add(esta, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 80, 240, -1));

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
       
        if(JforRangoDel.getText().equals("   -   -  -        ") ||
                txtIpto.getText().length()==0||
                jForRAngoAl.getText().equals("   -   -  -        ")||
                 calendarLim.getDate()==null||
                 jformaCai.getText().equals("                                    "))
                {
            JOptionPane.showMessageDialog(null, "Todos los campos son requeridos");
        }else{    
                    String rangoDel = JforRangoDel.getText();
                    String rangoAl = jForRAngoAl.getText();
                    int inicio = Integer.parseInt(rangoDel.split("-")[3]);
                    int fin = Integer.parseInt(rangoAl.split("-")[3]);
        if(fin>=inicio){
            int resta = inicio -1;
            String a = rangoDel.split("-")[0];
            String b = rangoDel.split("-")[1];
            String c = rangoDel.split("-")[2];
            String union = a+"-"+b+"-"+c+"-"+resta;

        Sentencias_Angel s = new Sentencias_Angel();
       double obtener = Double.parseDouble(this.txtIpto.getText());
       double div = obtener/100;
        s.setImpuesto_Sar(div);
        s.setRango_Del(this.JforRangoDel.getText());  
        s.setNum_Factura(union);
        s.setRango_Al(this.jForRAngoAl.getText());
        s.setCAI(this.jformaCai.getText());
        s.setFecha_Lim(((JTextField)this.calendarLim.getDateEditor().getUiComponent()).getText());
         
      
        if (Funciones_Angel.isRegisterSar(s)) {
            JOptionPane.showMessageDialog(null, "REGISTRO EXITOSO", "FUNCIONO", WIDTH);
            clean();
           Funciones_Angel.setListarSar("");
           lblId.setText(Funciones_Angel.extraerIdMaxSar());
//           
//            ;      
//            }
        } else {
            JOptionPane.showMessageDialog(null, "Fallo al Registrar", "ERROR", HEIGHT); 
                                            
                         }       
        }else{
            JOptionPane.showMessageDialog(null, "El rango final debe ser mayor que el rango inicial");
        }                    
    }//GEN-LAST:event_btnGuardarActionPerformed
}
        
    private void btnActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarActionPerformed
        // TODO add your handling code here:
        Sentencias_Angel s = new Sentencias_Angel();
        s.setId_Sar(Integer.parseInt(this.lblId.getText()));
       s.setRango_Del(this.JforRangoDel.getText());
        s.setRango_Al(this.jForRAngoAl.getText());
        s.setCAI(this.jformaCai.getText());
        s.setFecha_Lim(((JTextField)this.calendarLim.getDateEditor().getUiComponent()).getText());
        
        if (Funciones_Angel.isUpdateSar(s)) {
            JOptionPane.showMessageDialog(null, "Actualizacion Exitosa");
            Funciones_Angel.setListarSar("");
            lblId.setText(Funciones_Angel.extraerIdMaxSar());
            btnGuardar.setVisible(true);
            btnActualizar.setVisible(false);
            clean();
            
        } else {
            JOptionPane.showMessageDialog(null, "Error al Actualizar");
        }
        
    }//GEN-LAST:event_btnActualizarActionPerformed

    private void btnBorarrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBorarrActionPerformed
        // TODO add your handling code here:
        int fila = tblSAR.getSelectedRow();
        Sentencias_Angel s = new Sentencias_Angel();
       s.setId_Sar(Integer.parseInt(tblSAR.getValueAt(fila, 0).toString()));
           int f = JOptionPane.showConfirmDialog(null, "Desea Eliminar este Registro?", "Eliminar", WIDTH);
           
            if (f==JOptionPane.YES_NO_OPTION) {
                
                if (Funciones_Angel.isDeleteSar(s)) {
                    JOptionPane.showMessageDialog(null, "Se Elimino el dato SAR");
                    Funciones_Angel.setListarSar("");
                    
                }else{
                    JOptionPane.showMessageDialog(null, "No se Pudo Eliminar el Campo");
                }
                
            } else {
                JOptionPane.showMessageDialog(null, "Cancelado Exitoso");
            }
            
            
            
//        } else {
//            JOptionPane.showMessageDialog(null, "No se pudo borrar el campo");
//        }
        
    }//GEN-LAST:event_btnBorarrActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        clean();
        btnGuardar.setVisible(true);
        btnActualizar.setVisible(false);
        lblId.setText(Funciones_Angel.extraerIdMaxSar());
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jformaCaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jformaCaiActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jformaCaiActionPerformed

    private void jformaCaiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jformaCaiMouseClicked
        // TODO add your handling code here:
//        String rangoDel = JforRangoDel.getText();
//String[] parts = rangoDel.split("-");
//String part1 = parts[0]; 
//String part2 = parts[1]; 
//String part3 = parts[2];
//String part4 = parts[3];
//
// dpart1 = Integer.parseInt(part1);
// dpart2 = Integer.parseInt(part2);
// dpart3 = Integer.parseInt(part3);
// dpart4 = Integer.parseInt(part4);
//
//   String rangoAl = jForRAngoAl.getText();
//String[] parts2 = rangoAl.split("-");
//String part5 = parts[0]; 
//String part6 = parts[1]; 
//String part7 = parts[2];
//String part8 = parts[3];
//
// dpart5 = Integer.parseInt(part5);
// dpart6 = Integer.parseInt(part6);
// dpart7 = Integer.parseInt(part7);
// dpart8 = Integer.parseInt(part8);

    }//GEN-LAST:event_jformaCaiMouseClicked

    private void txtIptoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtIptoKeyReleased
//        double xd = Double.parseDouble(txtIpto.getText());
//        double s = xd/100;
//        res.setText(String.valueOf(s));
    }//GEN-LAST:event_txtIptoKeyReleased

    private void txtIptoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtIptoKeyTyped
       // Validaciones.Space(txtIpto.getText().length(), evt); 
        char c = evt.getKeyChar();
        if(c<'0' || c>'9') evt.consume();      
        
        int tam = txtIpto.getText().length();
        if(tam>=2){
            evt.consume();
        }
    }//GEN-LAST:event_txtIptoKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SAR.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SAR.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SAR.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SAR.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SAR().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JFormattedTextField JforRangoDel;
    private javax.swing.JButton btnActualizar;
    public static javax.swing.JButton btnBorarr;
    private javax.swing.JButton btnGuardar;
    public static com.toedter.calendar.JDateChooser calendarLim;
    private javax.swing.JTextField esta;
    private javax.swing.JButton jButton1;
    public static javax.swing.JFormattedTextField jForRAngoAl;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    public static javax.swing.JFormattedTextField jformaCai;
    private javax.swing.JLabel lblId;
    private javax.swing.JLabel res;
    public static javax.swing.JTable tblSAR;
    private javax.swing.JTextField txtIpto;
    // End of variables declaration//GEN-END:variables
}
