/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyectomp;

import java.awt.Event;
import java.awt.event.KeyEvent;
import java.text.SimpleDateFormat;
import javax.swing.InputMap;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.KeyStroke;
import javax.swing.table.DefaultTableModel;
import static proyectomp.SELECCIONAR_DEDUCCION.lbl;
import static proyectomp.SELECCIONAR_DEDUCCION.tblDedu;
import static proyectomp.Seleccionar_Bonificacioin.tblBoni;

/**
 *
 * @author Calix
 */
public class Seleccionar_Bonificacioin_Update extends javax.swing.JFrame {

    /**
     * Creates new form Seleccionar_Bonificacioin
     */
    public Seleccionar_Bonificacioin_Update() {
        initComponents();
        tblBoni.setSelectionMode(NORMAL);
         this.setResizable(false);
        InputMap map3 = txtValor.getInputMap(JTextField.WHEN_FOCUSED); 
    map3.put(KeyStroke.getKeyStroke(KeyEvent.VK_V, Event.CTRL_MASK), "null");
        tblBoni.getTableHeader().setReorderingAllowed(false);
        this.setLocationRelativeTo(null);
                  java.util.Date fecha = new java.util.Date();
               SimpleDateFormat formato = new SimpleDateFormat("yyy-MM-dd");
               fechaas.setText(formato.format(fecha));
       
        Funciones.setListarBONIUpdate("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txtValor = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblBoni = new javax.swing.JTable();
        SELECCIONAR = new javax.swing.JButton();
        fechaas = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        pagooo = new javax.swing.JLabel();
        idPlanilla = new javax.swing.JLabel();
        LBLEMP = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtValor.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtValorKeyTyped(evt);
            }
        });
        jPanel1.add(txtValor, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 40, 140, -1));

        tblBoni.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Id", "Nombre", "TDescripcion"
            }
        ));
        jScrollPane1.setViewportView(tblBoni);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 80, 500, 220));

        SELECCIONAR.setText("SELECCIONAR");
        SELECCIONAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SELECCIONARActionPerformed(evt);
            }
        });
        jPanel1.add(SELECCIONAR, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 340, -1, 42));
        jPanel1.add(fechaas, new org.netbeans.lib.awtextra.AbsoluteConstraints(389, 238, 51, 31));

        jLabel2.setText("Valor");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 40, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/fondo2.jpg"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 610, 450));

        pagooo.setText("jLabel1");
        jPanel1.add(pagooo, new org.netbeans.lib.awtextra.AbsoluteConstraints(317, 252, -1, -1));

        idPlanilla.setText("jLabel2");
        jPanel1.add(idPlanilla, new org.netbeans.lib.awtextra.AbsoluteConstraints(317, 286, -1, -1));

        LBLEMP.setText("1");
        jPanel1.add(LBLEMP, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 252, -1, -1));

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SELECCIONARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SELECCIONARActionPerformed
select();
//         int fila = tblBoni.getSelectedRow();
////        lblIdE.setText(tblDedu.getValueAt(fila, 0).toString());
//          
//        
//        Sentencias s = new Sentencias();
//        s.setId_Boni(Integer.parseInt(tblBoni.getValueAt(fila, 0).toString()));
//        s.setFK_Empleado(Integer.parseInt(this.LBLEMP.getText()));
//        s.setFK_Planilla(Integer.parseInt(this.idPlanilla.getText()));
//        s.setFecha(this.fechaas.getText());
//        
//        int a= JOptionPane.showConfirmDialog(null, "esta seguro que desea guardar esta bonificacion", "mostrar", JOptionPane.YES_NO_OPTION);
//        if (a==JOptionPane.YES_NO_OPTION) {
//            
//        
//        
//        
//        
//        if(Funciones.isRegistery_boni_planilla(s)){
//            
//            JOptionPane.showMessageDialog(this, "Funciono");
//            
//            //b.setId_Emp(Integer.parseInt(this.lbl.getText()));
//           Funciones.setListarJoinBoniUpdate(LBLEMP.getText(), idPlanilla.getText());
          Funciones.sumarColumnBoniUpdate();
          Funciones.sumarTotalAPagarUpdate();
//           dispose();
//            
//        }else{
//            JOptionPane.showMessageDialog(this, "Nada");
//            
//            
//        }
//        }else{
//            JOptionPane.showMessageDialog(null, "No se realizo el borrado");
//        }
    }//GEN-LAST:event_SELECCIONARActionPerformed

    private void txtValorKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtValorKeyTyped
        txtValor.setText(txtValor.getText().replaceAll("( )+", " "));
        
  char c = evt.getKeyChar();
        if(c<'0' || c>'9') evt.consume();      
        
        int tam = txtValor.getText().length();
        if(tam>=6){
            evt.consume();
        } 
    }//GEN-LAST:event_txtValorKeyTyped

    private void select(){
         int fila = tblBoni.getSelectedRow(); 
                   String Id, nombre, precio, cantidad, total;
           DefaultTableModel modelo = (DefaultTableModel) tblBoni.getModel();
           Id= tblBoni.getValueAt(fila, 0).toString();
           nombre= tblBoni.getValueAt(fila, 1).toString();
          // precio= tblBoni.getValueAt(fila, 2).toString();
           cantidad = txtValor.getText();
           int a =0;
       
        
       if (txtValor.getText().length()==0){
//                this.sexo.getSelectedItem().equals(0)||
//                this.TxtSue.getText().length()==0||
//                this.txtFun.getText().length()==0){
            JOptionPane.showMessageDialog(null, "Seleccione una cantidad");
            
        } else {
           
           for (int i = 0; i < DETALLE_PLANILLAS_UPDATE.tblBoni.getRowCount(); i++) {
               String val = DETALLE_PLANILLAS_UPDATE.tblBoni.getValueAt(i, 0).toString();
               if (Id.equals(val)) {
                   a=1;
               }
               
           }
           if (a>0) {
               JOptionPane.showMessageDialog(null, "Esta bonificacion ya fue seleccionada");
               
           } else {
               DefaultTableModel m = (DefaultTableModel)DETALLE_PLANILLAS_UPDATE.tblBoni.getModel();
   
           
           String filla[] = {Id, nombre, cantidad};
           m.addRow(filla);
           }
      }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Seleccionar_Bonificacioin_Update.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Seleccionar_Bonificacioin_Update.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Seleccionar_Bonificacioin_Update.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Seleccionar_Bonificacioin_Update.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Seleccionar_Bonificacioin_Update().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JLabel LBLEMP;
    private javax.swing.JButton SELECCIONAR;
    public static javax.swing.JLabel fechaas;
    public static javax.swing.JLabel idPlanilla;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    public static javax.swing.JLabel pagooo;
    public static javax.swing.JTable tblBoni;
    private javax.swing.JTextField txtValor;
    // End of variables declaration//GEN-END:variables
}
