/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package proyectomp;


import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author angel
 */
public class UPDATE_P extends javax.swing.JFrame {
   
    TableRowSorter trs;
//    DefaultTableModel m = (DefaultTableModel) tblInventario.getModel();
    

    /** Creates new form PRODUCTOS */
    public UPDATE_P() {
        
        initComponents();
        
        DefaultTableModel m = (DefaultTableModel) tblInventario.getModel();
        Funciones.setListarInventarioUpdate("");
         this.setExtendedState(MAXIMIZED_BOTH);
        
        lbId.setText(Funciones_Angel.extraerIdMax());
        this.setLocationRelativeTo(null);
//        comboTam.addItem("PERSONAL");
//        comboTam.addItem("FAMILIAR");
//        comboTam.addItem("MEDIO METRO");
//        
//        compiez.addItem("8 PIEZAS");
//        compiez.addItem("12 PIEZAS");
//        compiez.addItem("16 PIEZAS");
        
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblPro = new javax.swing.JTable();
        jLabel10 = new javax.swing.JLabel();
        CantidadMaterial = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblInventario = new javax.swing.JTable();
        xtxBuscar = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtNom = new javax.swing.JTextField();
        txtPrec = new javax.swing.JTextField();
        comboTam = new javax.swing.JComboBox<String>();
        jScrollPane1 = new javax.swing.JScrollPane();
        taDescr = new javax.swing.JTextArea();
        jLabel7 = new javax.swing.JLabel();
        lbId = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtExis = new javax.swing.JTextField();
        compiez = new javax.swing.JComboBox<String>();
        jLabel9 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setText("ACTUALIZAR");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(536, 537, 190, 70));

        tblPro.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Nombre", "Cantidad", "Unidad de medida"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblPro.setRowHeight(30);
        jScrollPane3.setViewportView(tblPro);

        jPanel1.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 369, 720, 150));

        jLabel10.setText("Cantidad");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(693, 146, -1, -1));

        CantidadMaterial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CantidadMaterialActionPerformed(evt);
            }
        });
        CantidadMaterial.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                CantidadMaterialKeyTyped(evt);
            }
        });
        jPanel1.add(CantidadMaterial, new org.netbeans.lib.awtextra.AbsoluteConstraints(778, 143, 50, -1));

        tblInventario.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Id", "Nombre", "Unidad de medida"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblInventario.setRowHeight(25);
        tblInventario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tblInventarioMousePressed(evt);
            }
        });
        jScrollPane2.setViewportView(tblInventario);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(499, 233, 650, 100));

        xtxBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                xtxBuscarActionPerformed(evt);
            }
        });
        xtxBuscar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                xtxBuscarKeyTyped(evt);
            }
        });
        jPanel1.add(xtxBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(552, 143, 131, -1));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setText("ACTUALIZAR PRODUCTO");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 3, -1, -1));

        jLabel2.setText("NOMBRE");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 114, -1, -1));

        jLabel3.setText("PRECIO");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 161, -1, -1));

        jLabel4.setText("DESCRIPCION");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 411, -1, -1));

        jLabel5.setText("TAMAÑO");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 216, -1, -1));

        jLabel6.setText("PIEZAS");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 319, -1, -1));

        txtNom.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNomKeyTyped(evt);
            }
        });
        jPanel1.add(txtNom, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 114, 281, -1));

        txtPrec.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtPrec.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtPrecKeyTyped(evt);
            }
        });
        jPanel1.add(txtPrec, new org.netbeans.lib.awtextra.AbsoluteConstraints(124, 161, 257, -1));

        comboTam.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Familiar", "Personal", "Medio Metro", " " }));
        jPanel1.add(comboTam, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 213, 281, -1));

        taDescr.setColumns(20);
        taDescr.setRows(5);
        taDescr.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                taDescrKeyTyped(evt);
            }
        });
        jScrollPane1.setViewportView(taDescr);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(97, 387, 284, 84));

        jLabel7.setText("ID");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, -1, -1));

        lbId.setText("1");
        jPanel1.add(lbId, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 67, 155, 20));

        jLabel8.setText("EXISTENCIA");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 364, -1, -1));

        txtExis.setEditable(false);
        txtExis.setText("0");
        txtExis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtExisActionPerformed(evt);
            }
        });
        jPanel1.add(txtExis, new org.netbeans.lib.awtextra.AbsoluteConstraints(103, 361, 281, -1));

        compiez.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "8", "12", "16" }));
        compiez.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                compiezActionPerformed(evt);
            }
        });
        jPanel1.add(compiez, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 313, 284, -1));

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel9.setText("MATERIALES");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(674, 74, 154, -1));

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel11.setText("L");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 163, -1, -1));

        jLabel12.setText("Buscar:");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(506, 146, -1, -1));

        jButton2.setText("X");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1219, 496, -1, -1));

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/fondo2.jpg"))); // NOI18N
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1270, 650));

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String name = Funciones.update_P(lbId.getText());
        String tama = Funciones.update_P_TA(lbId.getText());
        String num = Funciones.update_NUM(lbId.getText());
        if (txtNom.getText().equals(name)& comboTam.getSelectedItem().toString().equals(tama) & compiez.getSelectedItem().equals(num)) {
            Sentencias_Angel s = new Sentencias_Angel();
        s.setId_P(Integer.parseInt(this.lbId.getText()));
        s.setNombre_P(this.txtNom.getText());
        s.setPrecio_P(Double.parseDouble(this.txtPrec.getText()));
        s.setDescripcion_P(this.taDescr.getText());
        s.setTamanio_P(this.comboTam.getSelectedItem().toString());
        s.setNum_Piezas_P(this.compiez.getSelectedItem().toString()); 
        //s.setExistencia_P(Integer.parseInt(this.txtExis.getText()));
       
               
        if(Funciones_Angel.isUpdate_P(s)){
            JOptionPane.showMessageDialog(this, "Producto Actualizado");
            Funciones_Angel.setListar_P("");
            Funciones_Angel.isDelete_Detalle(s);
            GuadarDetalle();
            dispose();
        }else{
            JOptionPane.showMessageDialog(this, "No se pudo crear el Producto");
        }
        
        }
     String vali = Funciones.PruductoValidate(txtNom.getText(), comboTam.getSelectedItem().toString(), compiez.getSelectedItem().toString());
     
        if (vali.equals("1")) {
            JOptionPane.showMessageDialog(null, "Esta pizza ya fue registrada");
        }else{
        Sentencias_Angel s = new Sentencias_Angel();
        s.setId_P(Integer.parseInt(this.lbId.getText()));
        s.setNombre_P(this.txtNom.getText());
        s.setPrecio_P(Double.parseDouble(this.txtPrec.getText()));
        s.setDescripcion_P(this.taDescr.getText());
        s.setTamanio_P(this.comboTam.getSelectedItem().toString());
        s.setNum_Piezas_P(this.compiez.getSelectedItem().toString()); 
        //s.setExistencia_P(Integer.parseInt(this.txtExis.getText()));
       
               
        if(Funciones_Angel.isUpdate_P(s)){
            JOptionPane.showMessageDialog(this, "Producto Actualizado");
            Funciones_Angel.setListar_P("");
            Funciones_Angel.isDelete_Detalle(s);
            GuadarDetalle();
            dispose();
        }else{
            JOptionPane.showMessageDialog(this, "No se pudo crear el Producto");
        }
        
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void GuadarDetalle(){
        
        
        int fila = tblPro.getSelectedRow();
        int id_d = 0;
        Sentencias s = new Sentencias();
        //int id = Integer.parseInt(this.lbId.getText());
        //String id = s.setFK_Pro(Integer.parseInt(this.lbId.getText()));
        
        for (int i = 0; i < tblPro.getRowCount(); i++) {
            id_d++;
            s.setFK_IMP(Integer.parseInt(tblPro.getValueAt(i, 0).toString()));
        s.setCantidad_De_Pro(Double.parseDouble(tblPro.getValueAt(i, 2).toString()));
        //s.setId_De_Pro(id_d);
        s.setFK_Pro(Integer.parseInt(this.lbId.getText()));
        Funciones.isRegisterDetalle_Pro(s);
        
            
            
        }
        
        

    }
    private void compiezActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_compiezActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_compiezActionPerformed

    int count = 0;
    private void tblInventarioMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblInventarioMousePressed
       if(txtNom.getText().compareTo("") == 0 && txtPrec.getText().compareTo("") == 0 && taDescr.getText().compareTo("") == 0){
           JOptionPane.showMessageDialog(rootPane, "Ingrese los datos del producto", "Advertencia", JOptionPane.ERROR_MESSAGE);
       }else if(txtNom.getText().compareTo("") == 0 && txtPrec.getText().compareTo(txtPrec.getText()) == 0 && taDescr.getText().compareTo(taDescr.getText()) == 0){
           JOptionPane.showMessageDialog(rootPane, "Ingrese el nombre del producto", "Advertencia", JOptionPane.ERROR_MESSAGE);
       }else if(txtNom.getText().compareTo(txtNom.getText()) == 0 && txtPrec.getText().compareTo("") == 0 && taDescr.getText().compareTo(taDescr.getText()) == 0){
           JOptionPane.showMessageDialog(rootPane, "Ingrese el precio del producto", "Advertencia", JOptionPane.ERROR_MESSAGE);
       }else if(txtNom.getText().compareTo(txtNom.getText()) == 0 && txtPrec.getText().compareTo(txtPrec.getText()) == 0 && taDescr.getText().compareTo("") == 0){
           JOptionPane.showMessageDialog(rootPane, "Ingrese la descripcion del producto", "Advertencia", JOptionPane.ERROR_MESSAGE);
       } else{       
        int fila = tblInventario.getSelectedRow(); 
       count++;
        if (count==2) {
            int a =0;
        
       if (CantidadMaterial.getText().length()==0){
//                this.sexo.getSelectedItem().equals(0)||
//                this.TxtSue.getText().length()==0||
//                this.txtFun.getText().length()==0){
            JOptionPane.showMessageDialog(null, "Seleccione una cantidad");
            count=0;
        } else {
//       try{
           String Id, nombre, unidad, cantidad;
           DefaultTableModel modelo = (DefaultTableModel) tblInventario.getModel();
           Id= tblInventario.getValueAt(fila, 0).toString();
           nombre= tblInventario.getValueAt(fila, 1).toString();
           unidad= tblInventario.getValueAt(fila, 2).toString();
           cantidad = CantidadMaterial.getText();
           
           for(int i=0; i< tblPro.getRowCount(); i++){
            
            
            if(tblPro.getValueAt(i,0).toString().equals(Id)){
                a+=1;
              //JOptionPane.showMessageDialog(null, "Ya esta registrado");
            }
        }
        if(a>0){
            JOptionPane.showMessageDialog(null, "Ese producto ya a sido registrado");
            count=0;
            
        }else{ 
            
        
        
           
           
           DefaultTableModel m = (DefaultTableModel) tblPro.getModel();
            
//             while(m.getRowCount() > 0 ){
//                m.removeRow(0);
//                
//            }
           
           
           
           String filla[] = {Id, nombre, cantidad, unidad};
           m.addRow(filla);
           
           
           
//       }catch(Exception ex){
//           
//           
//       }
       CantidadMaterial.setText("");
       xtxBuscar.setText("");
       count=0;
       }
       }
            
        } 
        
      } 
    }//GEN-LAST:event_tblInventarioMousePressed

    private void xtxBuscarKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_xtxBuscarKeyTyped
        DefaultTableModel m = (DefaultTableModel) tblInventario.getModel();
        xtxBuscar.addKeyListener(new KeyAdapter() { 

            @Override
            public void keyReleased(KeyEvent ke) {
                trs.setRowFilter(RowFilter.regexFilter("(?i)"+xtxBuscar.getText(), 1));
                
                super.keyReleased(ke); //To change body of generated methods, choose Tools | Templates.
            }
        
        
        });
        trs = new TableRowSorter(m);
        tblInventario.setRowSorter(trs);
        
    }//GEN-LAST:event_xtxBuscarKeyTyped

    private void txtPrecKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPrecKeyTyped
char c = evt.getKeyChar();
        if(c<'0' || c>'9') evt.consume();      
        
        int tam = txtPrec.getText().length();
        if(tam>=6){
            evt.consume();
        }          
// TODO add your handling code here:
    }//GEN-LAST:event_txtPrecKeyTyped

    private void txtNomKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNomKeyTyped
char c = evt.getKeyChar();
         if(Character.isDigit(c)){
            getToolkit().beep();
            evt.consume();
         }
            int tam = txtNom.getText().length();
        if(tam>=30){
            evt.consume();
        }  else if((int)evt.getKeyChar()>32 && (int)evt.getKeyChar()<=47
                ||(int)evt.getKeyChar()>=58 && (int)evt.getKeyChar()<=64
                ||(int)evt.getKeyChar()>=91 && (int)evt.getKeyChar()<=96
                ||(int)evt.getKeyChar()>=123 && (int)evt.getKeyChar()<=163
                ||(int)evt.getKeyChar()>=166 && (int)evt.getKeyChar()<=255){
             getToolkit().beep();
            evt.consume();
        }        
// TODO add your handling code here:
    }//GEN-LAST:event_txtNomKeyTyped

    private void taDescrKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_taDescrKeyTyped
       char c = evt.getKeyChar();
         if(Character.isDigit(c)){
            getToolkit().beep();
            evt.consume();
         }
            int tam = taDescr.getText().length();
        if(tam>=250){
            evt.consume();
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_taDescrKeyTyped

    private void CantidadMaterialKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_CantidadMaterialKeyTyped
       char c = evt.getKeyChar();
        if(c<'0' || c>'9') evt.consume();      
        
        int tam = CantidadMaterial.getText().length();
        if(tam>=2){
            evt.consume();
        }  
        // TODO add your handling code here:
    }//GEN-LAST:event_CantidadMaterialKeyTyped

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
       int fila = tblPro.getSelectedRow();
       DefaultTableModel m = (DefaultTableModel) tblPro.getModel();
        m.removeRow(fila);
       
       
    }//GEN-LAST:event_jButton2ActionPerformed

    private void txtExisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtExisActionPerformed
        
    }//GEN-LAST:event_txtExisActionPerformed

    private void CantidadMaterialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CantidadMaterialActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CantidadMaterialActionPerformed

    private void xtxBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_xtxBuscarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_xtxBuscarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UPDATE_P.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UPDATE_P.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UPDATE_P.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UPDATE_P.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UPDATE_P().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField CantidadMaterial;
    public static javax.swing.JComboBox<String> comboTam;
    public static javax.swing.JComboBox<String> compiez;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    public static javax.swing.JLabel lbId;
    public static javax.swing.JTextArea taDescr;
    public static javax.swing.JTable tblInventario;
    public static javax.swing.JTable tblPro;
    public static javax.swing.JTextField txtExis;
    public static javax.swing.JTextField txtNom;
    public static javax.swing.JTextField txtPrec;
    private javax.swing.JTextField xtxBuscar;
    // End of variables declaration//GEN-END:variables

}
