/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyectomp;

import Reportes.Reportes;
import conexion.Conexion;
import java.awt.Event;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import java.math.BigDecimal;
import java.math.RoundingMode;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.DecimalFormat;
import java.text.SimpleDateFormat;
import java.util.HashMap;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.InputMap;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.KeyStroke;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;
import net.sf.jasperreports.engine.JRException;
import static proyectomp.EMPLEADOSS_CREAR.txtNombre;
import static proyectomp.LOCAL_REGISTRO.tblLocal;
import static proyectomp.MostrarVentas.tblMostrarVenta;

/**
 *
 * @author Calix
 */
public class VENTA extends javax.swing.JFrame {
    TableRowSorter trs;
     private static conexion.Conexion con = new Conexion();
    private static Connection conexion = con.getConexion();
    private  static PreparedStatement ps = null;

    /**
     * Creates new form VENTA
     */
    public VENTA() {
        initComponents();
        tblProductos.setSelectionMode(NORMAL);
        tblDetalle.setSelectionMode(NORMAL);
         InputMap map2 = TXTnombre.getInputMap(JTextField.WHEN_FOCUSED); 
    map2.put(KeyStroke.getKeyStroke(KeyEvent.VK_V, Event.CTRL_MASK), "null");
    InputMap maps = txtBuscar.getInputMap(JTextField.WHEN_FOCUSED); 
    maps.put(KeyStroke.getKeyStroke(KeyEvent.VK_V, Event.CTRL_MASK), "null");
    InputMap map3 = TXTapellido.getInputMap(JTextField.WHEN_FOCUSED); 
    map3.put(KeyStroke.getKeyStroke(KeyEvent.VK_V, Event.CTRL_MASK), "null");
    InputMap ma = TXTSEGDIR.getInputMap(JTextField.WHEN_FOCUSED); 
    ma.put(KeyStroke.getKeyStroke(KeyEvent.VK_V, Event.CTRL_MASK), "null");
    InputMap ma1 = txtCantidad.getInputMap(JTextField.WHEN_FOCUSED); 
    ma1.put(KeyStroke.getKeyStroke(KeyEvent.VK_V, Event.CTRL_MASK), "null");
         InputMap map4 = TXTdireccion.getInputMap(JTextField.WHEN_FOCUSED); 
    map4.put(KeyStroke.getKeyStroke(KeyEvent.VK_V, Event.CTRL_MASK), "null");
        tblProductos.getTableHeader().setReorderingAllowed(false);
        TXTdireccion.setLineWrap(true);
        TXTSEGDIR.setLineWrap(true);
        Funciones.setListarProductos("");
        txtFactura.setText(Funciones.extraerNumerofactura());
        this.setExtendedState(MAXIMIZED_BOTH);
        lblCount.setText(Funciones.extraerRangoMaximo());
        txtISV.setText(Funciones.extraerImpuesto());
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        TXTnombre = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        TXTapellido = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        cmbTipoDeVenta = new javax.swing.JComboBox();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TXTdireccion = new javax.swing.JTextArea();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        TXTSEGDIR = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblProductos = new javax.swing.JTable();
        txtBuscar = new javax.swing.JTextField();
        jScrollPane4 = new javax.swing.JScrollPane();
        tblDetalle = new javax.swing.JTable();
        btnGeneral = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        sub = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        txtISV = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        txtResu = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtFactura = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        txtCantidad = new javax.swing.JTextField();
        lblCount = new javax.swing.JLabel();
        TXTrtn = new javax.swing.JFormattedTextField();
        TXTtelefono = new javax.swing.JFormattedTextField();
        btnDelete = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("VENTAS");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 11, 130, -1));

        jLabel2.setText("Telefono");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 18, -1, -1));

        jLabel3.setText("Nombre");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 76, -1, -1));

        TXTnombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TXTnombreActionPerformed(evt);
            }
        });
        TXTnombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TXTnombreKeyTyped(evt);
            }
        });
        jPanel1.add(TXTnombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 96, 166, -1));

        jLabel4.setText("Apellidos");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 122, -1, -1));

        TXTapellido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TXTapellidoActionPerformed(evt);
            }
        });
        TXTapellido.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TXTapellidoKeyTyped(evt);
            }
        });
        jPanel1.add(TXTapellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 142, 166, -1));

        jLabel5.setText("RTN");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 168, -1, -1));

        jLabel6.setText("Tipo de venta");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(285, 42, -1, -1));

        cmbTipoDeVenta.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Local", "Domicilio" }));
        jPanel1.add(cmbTipoDeVenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(369, 39, -1, -1));

        jLabel7.setText("Direccion");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 214, -1, -1));

        TXTdireccion.setColumns(20);
        TXTdireccion.setRows(5);
        TXTdireccion.setNextFocusableComponent(TXTSEGDIR);
        TXTdireccion.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                TXTdireccionKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TXTdireccionKeyTyped(evt);
            }
        });
        jScrollPane1.setViewportView(TXTdireccion);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 234, 160, -1));

        jLabel8.setText("Segunda Direccion");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 336, -1, -1));

        TXTSEGDIR.setColumns(20);
        TXTSEGDIR.setRows(5);
        TXTSEGDIR.setNextFocusableComponent(txtBuscar);
        TXTSEGDIR.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                TXTSEGDIRKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TXTSEGDIRKeyTyped(evt);
            }
        });
        jScrollPane2.setViewportView(TXTSEGDIR);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 356, 160, -1));

        tblProductos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Id", "Nombre", "Precio"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblProductos.setRowHeight(30);
        tblProductos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblProductosMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tblProductos);

        jPanel1.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(206, 76, 727, 176));

        txtBuscar.setNextFocusableComponent(txtCantidad);
        txtBuscar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtBuscarKeyTyped(evt);
            }
        });
        jPanel1.add(txtBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(624, 39, 154, -1));

        tblDetalle.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Nombre", "Precio", "Cantidad", "Total"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblDetalle.setRowHeight(30);
        jScrollPane4.setViewportView(tblDetalle);

        jPanel1.add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(206, 336, 727, 222));

        btnGeneral.setText("GENERAR VENTA");
        btnGeneral.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGeneralActionPerformed(evt);
            }
        });
        jPanel1.add(btnGeneral, new org.netbeans.lib.awtextra.AbsoluteConstraints(536, 601, 180, 69));

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel9.setText("SUB TOTAL");

        sub.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        sub.setText("0");

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel11.setText("L");

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel12.setText("ISV");

        txtISV.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel14.setText("TOTAL");

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel15.setText("L");

        txtResu.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtResu.setText("0");

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel10.setText("Nro FACTURA");

        txtFactura.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtFactura.setText("123-4553-2333");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(27, 27, 27)
                                .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(27, 27, 27)
                                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel12))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(sub, javax.swing.GroupLayout.DEFAULT_SIZE, 64, Short.MAX_VALUE)
                            .addComponent(txtISV, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtResu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addGap(34, 34, 34)
                        .addComponent(txtFactura)))
                .addContainerGap(49, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(txtFactura))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sub, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtISV, javax.swing.GroupLayout.DEFAULT_SIZE, 51, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtResu, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(230, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(943, 11, 330, -1));

        jLabel17.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel17.setText("VENTA DEL PRODUCTO");
        jPanel1.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 270, -1, 60));

        txtCantidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCantidadActionPerformed(evt);
            }
        });
        txtCantidad.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCantidadKeyTyped(evt);
            }
        });
        jPanel1.add(txtCantidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 40, 70, -1));

        lblCount.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblCount.setForeground(new java.awt.Color(255, 0, 51));
        lblCount.setText("ewewe");
        jPanel1.add(lblCount, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 601, 446, 40));

        try {
            TXTrtn.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("####-####-#####-#")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jPanel1.add(TXTrtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 183, 166, -1));

        try {
            TXTtelefono.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        TXTtelefono.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        TXTtelefono.setNextFocusableComponent(TXTnombre);
        TXTtelefono.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TXTtelefonoActionPerformed(evt);
            }
        });
        TXTtelefono.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                TXTtelefonoKeyPressed(evt);
            }
        });
        jPanel1.add(TXTtelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 48, 166, -1));

        btnDelete.setText("X");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });
        jPanel1.add(btnDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(943, 535, -1, -1));

        jButton1.setText("...");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(186, 47, 22, -1));

        jLabel13.setText("Cantidad");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(796, 42, -1, -1));

        jLabel16.setText("Buscar por nombre");
        jPanel1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(516, 42, -1, -1));

        jLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/fondo2.jpg"))); // NOI18N
        jPanel1.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1330, 770));

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    int a = 0;
    private void btnGeneralActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGeneralActionPerformed
       double acumulador=0;
        if(TXTtelefono.getText().equals("    -    ")|| 
                this.TXTnombre.getText().length()==0||
                this.tblDetalle.getRowCount()==0||
                this.TXTapellido.getText().length()==0){
                JOptionPane.showMessageDialog(this, "Debe Ingresar Todos Los Datos", "Datos Incompletos", JOptionPane.ERROR_MESSAGE);
               }else{
           
                   int fila = tblDetalle.getSelectedRow();
        
        Sentencias s = new Sentencias();
        
        
        
           
           
        
//        for(int i=0; i< tblDetalle.getRowCount(); i++){
//        s.setId_P(Integer.parseInt(tblDetalle.getValueAt(i, 0).toString()));
//        
//         String sql = "SELECT * FROM DETALLE_PRODUCTO WHERE FK_Pro=?";
//                try{
//        
//            Statement st = conexion.createStatement();
//            
//            ps = conexion.prepareStatement(sql);
//            ps.setInt(1, s.getId_P());
//            ResultSet rs = ps.executeQuery();
//            
//             while(rs.next()){
//                s.setFK_IMP(rs.getInt(3));
//                s.setCantidad_De_Pro(rs.getDouble(2));
//                double Q = s.getCantidad_De_Pro();
//                double Q1 = Double.parseDouble(tblDetalle.getValueAt(i, 3).toString());
//                double total = Q*Q1;
//                Funciones.setConsultarExistencia(s);
//                double existencia = s.getExistencia_IMP();
//                
//                
//                if (existencia<total) {
//              a++;
//               
//                    
//                } 
//                //acumulador = acumulador+total;
//                
//            }
//                }catch(SQLException e){
//                    
//                }
//        }
            
            
             Sentencias_Angel sa= new Sentencias_Angel();
                         
            sa.setTelefono_CL(TXTtelefono.getText());
            Funciones_Angel.setListarCliente(sa);
            
            if (sa.getTelefono_CL_C()!=null) {
                sa.setNombre_CL(TXTnombre.getText());
                sa.setApellidos_CL(TXTapellido.getText());
                sa.setRTN(TXTrtn.getText());
                sa.setDireccion_CL(TXTdireccion.getText());
                sa.setSegunda_Direccion(TXTSEGDIR.getText());
                
                if(Funciones_Angel.isUpdate(sa)){
                    //JOptionPane.showMessageDialog(null, "Actualizado");
                     Venta();
                     String d = Funciones.extraerIdMaxSAR();
                     sa.setNum_Factura(txtFactura.getText());
                     //JOptionPane.showMessageDialog(null, d);
                     sa.setId_Sar(Integer.parseInt(d));
                      if (cmbTipoDeVenta.getSelectedItem().toString().equals("Domicilio")) {
                    //JOptionPane.showMessageDialog(null, "nada");
                } else {
                     Funciones_Angel.isUpdateSar(sa);
                }
                     
                     
                     obtener();
                     limpiar();

        
        
                    
                }} else{

              sa.setTelefono_CL(TXTtelefono.getText());
                sa.setNombre_CL(TXTnombre.getText());
                sa.setApellidos_CL(TXTapellido.getText());
                sa.setRTN(TXTrtn.getText());
                sa.setDireccion_CL(TXTdireccion.getText());
                sa.setSegunda_Direccion(TXTSEGDIR.getText());
            if(Funciones_Angel.isRegister(sa)){
               // Funciones.setListar("");
               // JOptionPane.showMessageDialog(this, "Nuevo Cliente Registrado");
                 Venta();
                   String d = Funciones.extraerIdMaxSAR();
                     sa.setNum_Factura(txtFactura.getText());
                    
                     sa.setId_Sar(Integer.parseInt(d));
                 if (cmbTipoDeVenta.getSelectedItem().toString().equals("Domicilio")) {
                   // JOptionPane.showMessageDialog(null, "nada");
                } else {
                     Funciones_Angel.isUpdateSar(sa);
                }
                     
                 obtener();
                 limpiar();
            }}

                        
                    
                        
                    
                    
                    
        }
           
     
      
    
    }//GEN-LAST:event_btnGeneralActionPerformed

    private void Venta(){
        String fechaa = null;
        java.util.Date fecha = new java.util.Date();
               SimpleDateFormat formato = new SimpleDateFormat("yyy-MM-dd");
               fechaa = formato.format(fecha);
        Sentencias s = new Sentencias();   
        s.setFecha_VV(fechaa);
        String facturas = Funciones.extraerNumerofactura();
        s.setNo_Factura_VV(facturas);
        //s.setNo_Factura_VV(this.txtFactura.getText());
        s.setTelefon_CL(this.TXTtelefono.getText());
        s.setTipo_V(this.cmbTipoDeVenta.getSelectedItem().toString());
        s.setTotal(Double.parseDouble(txtResu.getText()));
        s.setSubTotal_V(Double.parseDouble(sub.getText()));
        s.setImpto_V(Double.parseDouble(txtISV.getText()));
               
        if(Funciones.isRegisterVenta(s)){
            //GuadarDetalle();
        }else{
            JOptionPane.showMessageDialog(this, "No se pudo Realizar la venta");
        }
    }                  
    private void obtener(){
        String idd = Funciones.extraerVentaMax();
        Sentencias s = new Sentencias();
        
        for(int i=0; i< tblDetalle.getRowCount(); i++){
        s.setId_P(Integer.parseInt(tblDetalle.getValueAt(i, 0).toString()));
        
         String sql = "SELECT * FROM DETALLE_PRODUCTO WHERE FK_Pro=?";
                try{
        
            Statement st = conexion.createStatement();
            
            ps = conexion.prepareStatement(sql);
            ps.setInt(1, s.getId_P());
            ResultSet rs = ps.executeQuery();
        while(rs.next()){
            
                s.setFK_IMP(rs.getInt(3));
                s.setCantidad_De_Pro(rs.getDouble(2));
                double Q = s.getCantidad_De_Pro();
                double Q1 = Double.parseDouble(tblDetalle.getValueAt(i, 3).toString());
                double total = Q*Q1;
                Funciones.setConsultarExistencia(s);
                double existencia = s.getExistencia_IMP();
                double deduccion = existencia-total;
                
                
//               JOptionPane.showMessageDialog(null, "la existencia es" +existencia);
//               JOptionPane.showMessageDialog(null, s.getCantidad_De_Pro());
//               JOptionPane.showMessageDialog(null, Q1);
//               JOptionPane.showMessageDialog(null, total);
//               JOptionPane.showMessageDialog(null, "la nueva existencia seria" +deduccion);
             
               
//               s.setCantidad_V(Integer.parseInt(tblDetalle.getValueAt(i, 3).toString()));
//               s.setFk_vv(Integer.parseInt(idd));
//               s.setId_P(Integer.parseInt(tblDetalle.getValueAt(i, 0).toString()));
//               s.setGasto_Materiales_V(total);
               s.setCantidad_De_Pro(deduccion);
        //Funciones.isRegisterDetalle_Venta(s);
        
          Funciones.isUpdateInventarioVenta(s);   
            }
                  
                        s.setCantidad_V(Integer.parseInt(tblDetalle.getValueAt(i, 3).toString()));
                        s.setFk_vv(Integer.parseInt(idd));
                        s.setId_P(Integer.parseInt(tblDetalle.getValueAt(i, 0).toString()));
                       Funciones.isRegisterDetalle_Venta(s); 
                    
       
        }catch (SQLException ex){
            Logger.getLogger(Funciones.class.getName()).log(Level.SEVERE, null, ex);
            
        }
        
    }
    }
    
    int count =0;
    int condicion = 0;
    private void tblProductosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblProductosMouseClicked
              int fila = tblProductos.getSelectedRow(); 
              int cero = 0;
              Sentencias s = new Sentencias();
       count++;
        if (count==2) {
            int a =0;
            
            
            
//        
//       if (txtCantidad.getText().length()==0){
////                this.sexo.getSelectedItem().equals(0)||
////                this.TxtSue.getText().length()==0||
////                this.txtFun.getText().length()==0){
//           cero=1;
//            //JOptionPane.showMessageDialog(null, "Seleccione una cantidad");
//            //count=0;
//            
           
//       try{
           String Id, nombre, precio, cantidad, total;
           DefaultTableModel modelo = (DefaultTableModel) tblProductos.getModel();
           Id= tblProductos.getValueAt(fila, 0).toString();
           nombre= tblProductos.getValueAt(fila, 1).toString();
           precio= tblProductos.getValueAt(fila, 2).toString();
           cantidad = txtCantidad.getText();
            if (txtCantidad.getText().length()==0) {
                cantidad = "1";
                
            }else{
               cantidad = txtCantidad.getText(); 
            }
           
           
           for(int i=0; i< tblDetalle.getRowCount(); i++){
            
            
            if(tblDetalle.getValueAt(i,0).toString().equals(Id)){
                a+=1;
            }
        }
        if(a>0){
            JOptionPane.showMessageDialog(null, "Ese producto ya a sido registrado");
            count =0;
            
        }else{
            s.setId_P(Integer.parseInt(tblProductos.getValueAt(fila, 0).toString()));
            
            
                     String sql = "SELECT * FROM DETALLE_PRODUCTO WHERE FK_Pro=?";
                try{
        
            Statement st = conexion.createStatement();
            
            ps = conexion.prepareStatement(sql);
            ps.setInt(1, s.getId_P());
            ResultSet rs = ps.executeQuery();
            
             while(rs.next()){
                s.setFK_IMP(rs.getInt(3));
                s.setCantidad_De_Pro(rs.getDouble(2));
                double Q = s.getCantidad_De_Pro();
               // double Q1 = Double.parseDouble(txtCantidad.getText());
                double Q1 = Double.parseDouble(cantidad);
                //double Q1 = Double.parseDouble(tblDetalle.getValueAt(i, 3).toString());
                double totales = Q*Q1;
                Funciones.setConsultarExistencia(s);
                double existencia = s.getExistencia_IMP();
                //JOptionPane.showMessageDialog(null, existencia);
                
                if (existencia<totales) {
              condicion++;
               
                    
                } 
                //acumulador = acumulador+total;
                
            }
                }catch(SQLException e){
                    JOptionPane.showMessageDialog(null, "No da");
                    
                }
        
            
            
                    if (condicion>=1) {
                        JOptionPane.showMessageDialog(null, "No cuenta con los suficientes materiales");
                        a=0; 
                        condicion=0;
                        count=0;
                        //acumulador=0;
                    }else { 
                        
                    
            
            
            
        
        
           
           
           DefaultTableModel m = (DefaultTableModel) tblDetalle.getModel();
            
//             while(m.getRowCount() > 0 ){
//                m.removeRow(0);
//                
//            }
           
           
           double suma = Double.parseDouble(precio)* Double.parseDouble(cantidad);
           String resultado = String.valueOf(suma);
           
           
           
           String filla[] = {Id, nombre, precio, cantidad, resultado};
           m.addRow(filla);
           suma();
     
          
           
           
           count=0;
        //   txtCantidad.setText(null);
           
           
           
//       }catch(Exception ex){
//           
//           
//       }
      }
       }
       
            
        }
    }//GEN-LAST:event_tblProductosMouseClicked

    private void suma(){
        DefaultTableModel m = (DefaultTableModel) tblDetalle.getModel();
        double valor = 0;
        double total = 0;
        
        for (int i = 0; i < tblDetalle.getRowCount(); i++) {
            double dato = Double.parseDouble(tblDetalle.getValueAt(i, 4).toString());
            total +=dato;    
        }
        txtResu.setText(String.valueOf(total));
        
             double subTotal= Double.parseDouble(txtResu.getText());
          //double isv = Double.parseDouble(txtISV.getText());
          double mame = Double.parseDouble(Funciones.extraerImpuesto());
          double alm = mame+1;
          double Total = subTotal/alm;
          //double s = Math.round(Total*10000d)/10000;
          
          BigDecimal jaja = new BigDecimal(Total);
          jaja = jaja.setScale(2, RoundingMode.HALF_UP);
//          DecimalFormat d = new DecimalFormat("#####,##");
//          String formated = d.format(Total);
          
          
          
          
          sub.setText(String.valueOf(jaja));
          
          double impto = Double.parseDouble(sub.getText());
          double alma = Double.parseDouble(Funciones.extraerImpuesto());
          float imptos = (float) (impto*alma);
          txtISV.setText(String.valueOf(imptos));
    }
    private void limpiar(){
        
        try {
            Reportes reporte = new Reportes();
             HashMap datos = new HashMap();
             datos.put("id", Integer.parseInt(Funciones.extraerVentaMax()));
             datos.put("idl", Integer.parseInt(Funciones_Henry.extraerIdMaxLocal()));
             datos.put("idsar", Integer.parseInt(Funciones_Henry.extraerIdMaxSAR()));
             datos.put("idcl", TXTtelefono.getText());
             reporte.ReporteVenta(datos);
        } catch (JRException ex) {
            Logger.getLogger(Reportes.class.getName()).log(Level.SEVERE, null, ex);
        } catch(SQLException ex){
            Logger.getLogger(Reportes.class.getName()).log(Level.SEVERE, null, ex);
        }
        
         DefaultTableModel modelo = (DefaultTableModel)tblDetalle.getModel();
            
            //modelo.fireTableDataChanged();
 
            
            while(modelo.getRowCount() > 0 ){
                modelo.removeRow(0);
                
            }
            TXTtelefono.setText(null);
            TXTnombre.setText(null);
            TXTapellido.setText(null);
            TXTdireccion.setText(null);
            TXTSEGDIR.setText(null);
            TXTrtn.setText(null);
            txtISV.setText(null);
            sub.setText(null);
            txtCantidad.setText(null);
            txtResu.setText(null);
            TXTrtn.setText(null);
            lblCount.setText(Funciones.extraerRangoMaximo());
           // Funciones.extraerRangoMaximo();
            txtFactura.setText(Funciones.extraerNumerofactura());
            
            
      
           
    }
    private void TXTnombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TXTnombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TXTnombreActionPerformed

    private void TXTapellidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TXTapellidoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TXTapellidoActionPerformed

    private void txtBuscarKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBuscarKeyTyped
txtBuscar.setText(txtBuscar.getText().replaceAll("( )+", " "));
        Validaciones.Space(txtBuscar.getText().length(), evt);        DefaultTableModel m = (DefaultTableModel) tblProductos.getModel();
        txtBuscar.addKeyListener(new KeyAdapter() { 

            @Override
            public void keyReleased(KeyEvent ke) {
                trs.setRowFilter(RowFilter.regexFilter("(?i)"+txtBuscar.getText(), 1));
                
                super.keyReleased(ke); //To change body of generated methods, choose Tools | Templates.
            }
        
        
        });
        trs = new TableRowSorter(m);
        tblProductos.setRowSorter(trs);
    }//GEN-LAST:event_txtBuscarKeyTyped

    private void TXTnombreKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TXTnombreKeyTyped
JTextField txtnombre = (JTextField)evt.getComponent();

String texto=txtnombre.getText();//.trim();//para evitar espacios en blanco antes y despues del texto
if(texto.length()>0){
char primero=texto.charAt(0);
texto=Character.toUpperCase(primero)+texto.substring(1, texto.length());
txtnombre.setText(texto);
}
TXTnombre.setText(TXTnombre.getText().replaceAll("( )+", " "));
        Validaciones.Space(TXTnombre.getText().length(), evt);
        char l = evt.getKeyChar();
         
        if(Character.isDigit(l)){
            getToolkit().beep();
            evt.consume();
        }
       
            int tam = TXTnombre.getText().length();
        if(tam>=30){
            evt.consume();
        }  
    
        else if((int)evt.getKeyChar()>32 && (int)evt.getKeyChar()<=47
                ||(int)evt.getKeyChar()>=58 && (int)evt.getKeyChar()<=64
                ||(int)evt.getKeyChar()>=91 && (int)evt.getKeyChar()<=96
                ||(int)evt.getKeyChar()>=123 && (int)evt.getKeyChar()<=163
                ||(int)evt.getKeyChar()>=166 && (int)evt.getKeyChar()<=255){
             getToolkit().beep();
            evt.consume();
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_TXTnombreKeyTyped

    private void TXTapellidoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TXTapellidoKeyTyped
JTextField txtnombre = (JTextField)evt.getComponent();

String texto=txtnombre.getText();//.trim();//para evitar espacios en blanco antes y despues del texto
if(texto.length()>0){
char primero=texto.charAt(0);
texto=Character.toUpperCase(primero)+texto.substring(1, texto.length());
txtnombre.setText(texto);
}
TXTapellido.setText(TXTapellido.getText().replaceAll("( )+", " "));
        Validaciones.Space(TXTapellido.getText().length(), evt);
        char l = evt.getKeyChar();
         
        if(Character.isDigit(l)){
            getToolkit().beep();
            evt.consume();
        }
       
            int tam = TXTapellido.getText().length();
        if(tam>=30){
            evt.consume();
        }  
    
        else if((int)evt.getKeyChar()>32 && (int)evt.getKeyChar()<=47
                ||(int)evt.getKeyChar()>=58 && (int)evt.getKeyChar()<=64
                ||(int)evt.getKeyChar()>=91 && (int)evt.getKeyChar()<=96
                ||(int)evt.getKeyChar()>=123 && (int)evt.getKeyChar()<=163
                ||(int)evt.getKeyChar()>=166 && (int)evt.getKeyChar()<=255){
             getToolkit().beep();
            evt.consume();
        }// TODO add your handling code here:
    }//GEN-LAST:event_TXTapellidoKeyTyped

    private void TXTtelefonoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TXTtelefonoActionPerformed
       
        Sentencias_Angel s = new Sentencias_Angel();
        
       s.setTelefono_CL(TXTtelefono.getText());
       Funciones_Angel.setListarCliente(s);
        
        if (s.getTelefono_CL().equals(TXTtelefono.getText())) {
            TXTnombre.setText(s.getNombre_CL());
            TXTapellido.setText(s.getApellidos_CL());
            TXTdireccion.setText(s.getDireccion_CL());
            TXTrtn.setText(s.getRTN());
            TXTSEGDIR.setText(s.getSegunda_Direccion());
            
        }else{
            TXTnombre.setText(s.getNombre_CL());
            
        }
    }//GEN-LAST:event_TXTtelefonoActionPerformed

    private void TXTtelefonoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TXTtelefonoKeyPressed

    }//GEN-LAST:event_TXTtelefonoKeyPressed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
       int fila = tblDetalle.getSelectedRow();
       DefaultTableModel m = (DefaultTableModel) tblDetalle.getModel();
        m.removeRow(fila);
        suma();
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        TXTtelefono.setText("1234-5678");
        TXTnombre.setText("Consumidor");
        TXTapellido.setText("Final");
    }//GEN-LAST:event_jButton1ActionPerformed

    private void txtCantidadKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCantidadKeyTyped

        char c = evt.getKeyChar();
        if(c<'0' || c>'9') evt.consume();      
        
        int tam = txtCantidad.getText().length();
        if(tam>=6){
            evt.consume();
        }        // TODO add your handling code here:
    }//GEN-LAST:event_txtCantidadKeyTyped

    private void txtCantidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCantidadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCantidadActionPerformed

    private void TXTdireccionKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TXTdireccionKeyTyped
       TXTdireccion.setText(TXTdireccion.getText().replaceAll("( )+", " "));
        Validaciones.Space(TXTdireccion.getText().length(), evt);
         int tam = TXTdireccion.getText().length();  
        if(tam>=300){
            evt.consume();
     }
    }//GEN-LAST:event_TXTdireccionKeyTyped

    private void TXTSEGDIRKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TXTSEGDIRKeyTyped
TXTSEGDIR.setText(TXTSEGDIR.getText().replaceAll("( )+", " "));
        Validaciones.Space(TXTSEGDIR.getText().length(), evt);   
         int tam = TXTSEGDIR.getText().length();  
        if(tam>=300){
            evt.consume();
     }
    }//GEN-LAST:event_TXTSEGDIRKeyTyped

    private void TXTdireccionKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TXTdireccionKeyPressed
 if (evt.getKeyCode() == KeyEvent.VK_TAB) {
                    if (evt.getModifiers() > 0) {
                        TXTdireccion.transferFocusBackward();
                    } else {
                        TXTdireccion.transferFocus();
                    }
                    evt.consume();
                }        // TODO add your handling code here:
    }//GEN-LAST:event_TXTdireccionKeyPressed

    private void TXTSEGDIRKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TXTSEGDIRKeyPressed
 if (evt.getKeyCode() == KeyEvent.VK_TAB) {
                    if (evt.getModifiers() > 0) {
                        TXTSEGDIR.transferFocusBackward();
                    } else {
                        TXTSEGDIR.transferFocus();
                    }
                    evt.consume();
                }        // TODO add your handling code here:
    }//GEN-LAST:event_TXTSEGDIRKeyPressed

    private void validar(){
               
    
}
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VENTA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VENTA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VENTA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VENTA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VENTA().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JTextArea TXTSEGDIR;
    public static javax.swing.JTextField TXTapellido;
    public static javax.swing.JTextArea TXTdireccion;
    public static javax.swing.JTextField TXTnombre;
    public static javax.swing.JFormattedTextField TXTrtn;
    public static javax.swing.JFormattedTextField TXTtelefono;
    private javax.swing.JButton btnDelete;
    public static javax.swing.JButton btnGeneral;
    private javax.swing.JComboBox cmbTipoDeVenta;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JLabel lblCount;
    private javax.swing.JLabel sub;
    private javax.swing.JTable tblDetalle;
    public static javax.swing.JTable tblProductos;
    private javax.swing.JTextField txtBuscar;
    public static javax.swing.JTextField txtCantidad;
    private javax.swing.JLabel txtFactura;
    private javax.swing.JLabel txtISV;
    private javax.swing.JLabel txtResu;
    // End of variables declaration//GEN-END:variables
}
